### ISSUE TITLE
http functions don't work unless extension installed in public

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-http#10]
Okay I finally got this extension to work after figuring out my issue.

I have a schema called contrib which is part of my search path.

If I install http extension in the contrib schema and then do something like

```
SELECT (unnest(headers)).* FROM http_get('http://myserver');

```

I get error:

```
ERROR:  cache lookup failed for type 0

```

However if I then do:
```
ALTER EXTENSION http SET SCHEMA public;

```

Then it works fine

**Comment by pramsey** [comment]
If you set your search path into `contrib` does it work then?

**Comment by robe2** [comment]
No I alreadyhave contrib in my search path. That's where most of my extensions are installed.

**Comment by pramsey** [comment]
I blame unnest

**Comment by robe2** [comment]
nah unnest is not at fault

```

SELECT content FROM contrib.http_get('http://myserver');

```

does the same thing

Hey I noticed your lookup_type_oid code has this line:

```
	Oid namesp = LookupExplicitNamespace("public", false);
```

What does that mean?

**Comment by pramsey** [comment]
means you're smarter than me

**Comment by denvertimothy** [comment]
I had the same problem:

`ERROR:  cache lookup failed for type 0`

Setting the schema to `public` solved the problem:

`alter extension http set schema public;`
