### ISSUE TITLE
If I have 15k URLs to process, is there a recommended approach to get all the contents?

### ISSUE THREAD

**Issue by majestique** [pramsey/pgsql-http#100]
My thoughts would be:
- decrease timeout time to 20 seconds
- get multiple core server (maybe at least 16) and set the cores for parallel processing
- break the process out in batches (say 100 URLs at a time)
 
Has anyone attempted to process thousands of links yet? What challenges and solutions have you come across? 

Is it not recommended I handle this many URLs with this utility?

**Comment by pramsey** [comment]
The difficulty of error handling, the single thread, all mitigate against doing bulk retrieval using pgsql-http. I would tend towards some python library or specific scraping tools. I've held out dreams of some kind of async implementation that would make scaling up and non-blocking in this utility but have yet to realize it.

**Comment by majestique** [comment]
Looks like this might be the solution for large projects: https://github.com/thomasdondorf/puppeteer-cluster

**Comment by pramsey** [comment]
Probably overkill unless the pages you are scraping are heavy in JS and need to be interacted with to sneak past scraping guards. I personally used https://scrapy.org/ when I had large scraping tasks.
