### ISSUE TITLE
Option for http retries

### ISSUE THREAD

**Issue by nextstopsun** [pramsey/pgsql-http#101]
Can http function accept an optional `retries` parameter to retry a http request N times in case it fails on timeout or else?

**Comment by pramsey** [comment]
I’ve tried to restrict the extension to doing things that Curl does, so it’s just a light wrapper with little or no moving parts of its own. So to put it back on you: is there a curl option for that?

**Comment by nextstopsun** [comment]
Ah, seems like it's available out of the box with curl `retry` option.

**Comment by nextstopsun** [comment]
Are `--retry` and friends exposed to `CURLOPTS`?

**Comment by pramsey** [comment]
No, it seems they are implemented in the curl command-line utility, not in the library. Here's the opts we have to work with. https://curl.haxx.se/libcurl/c/easy_setopt_options.html
