### ISSUE TITLE
Article on boundlessgeo is no longer available 

### ISSUE THREAD

**Issue by steve-chavez** [pramsey/pgsql-http#102]
http://boundlessgeo.com/2012/04/http-for-postgresql/ now redirects to https://www.planet.com.

That was a great article explaining the usage of the extension, is there an alternative url?

Tried wayback machine with no luck.

**Comment by pramsey** [comment]
Nope, unless you can find another cache, it's probably lost. I have no local copy.

**Comment by pramsey** [comment]
(Let me know if you do, I'll republish it on my personal.)

**Comment by steve-chavez** [comment]
Don't know of any other cache. If it's likely lost then I suggest removing the boundlessgeo link from https://github.com/pramsey/pgsql-http#motivation (to prevent confusion).
