### ISSUE TITLE
CURLOPT_SSL_VERIFYPEER working in postgres 11 not in postgres 9.5

### ISSUE THREAD

**Issue by mostafa-kamal** [pramsey/pgsql-http#104]
`select http_set_curlopt('CURLOPT_SSL_VERIFYPEER', '0');`

While trying to configure CURLOPT_SSL_VERIFYPEER from postgres 11 using above code block it works perfectly, However, while i am trying out from postgres 9.5, i get the following error: 

> ERROR:  curl option 'CURLOPT_SSL_VERIFYPEER' is not available for run-time configuration

Both postgres server are hosted in same machine.

**Comment by pramsey** [comment]
Probably you have difference versions of the 'http' extension installed on that machine. They may be backed by the same libcurl, but earlier versions of the extension supported a more limited set of options that the user could set.
