### ISSUE TITLE
Doesn't compile against PostgreSQL 12

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-http#106]
Was trying to compile against PostgreSQL 12beta3 shipped by apt.postgresql.org  and I get this:

> http.c: In function ‘typname_get_tupledesc’:
> http.c:594:49: error: macro "GetSysCacheOid2" requires 4 arguments, but only 3 given
>                    ObjectIdGetDatum(typnamespace));
>                                                  ^
> http.c:592:16: error: ‘GetSysCacheOid2’ undeclared (first use in this function); did you mean ‘GetSysCacheOid’?
>    Oid typoid = GetSysCacheOid2(TYPENAMENSP,
>                 ^~~~~~~~~~~~~~~
>                 GetSysCacheOid
> http.c:592:16: note: each undeclared identifier is reported only once for each function it appears in
> http.c:591:7: warning: unused variable ‘typnamespace’ [-Wunused-variable]
>    Oid typnamespace = lfirst_oid(l);
>        ^~~~~~~~~~~~
> <builtin>: recipe for target 'http.o' failed

I haven't tried on windows yet, but assume I'll run into the same issue.

**Comment by robe2** [comment]
Nevermind user error -- I was trying to compile against your last released 1.3.0 which doesn't work with pg12.  Any chance you can make another release pretty please :)

**Comment by pramsey** [comment]
I cut a 1.3.1 release
