### ISSUE TITLE
Cant install on PG 9.2 64 bits

### ISSUE THREAD

**Issue by neslip** [pramsey/pgsql-http#11]
Hi pramsey,

I cant install the client on my postgresql server :(
I follow the instructions but nothing. Error.
My Postgresql version is: PostgreSQL 9.2.4 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-3), 64-bit

Apparently its an error with "htup_details.h"

Please help!
Regards

**Comment by pramsey** [comment]
You'll have to paste in the whole error message. Sounds like a PgSQL version problem, I've probably baked in an assumption of PgSQL 9.3+

**Comment by robe2** [comment]
pramsey,

I think you are missing the pg htup_details.h > 9.3 check wrap around this line

https://github.com/pramsey/pgsql-http/blob/master/http.c#L44

Similar to what we have in PostGIS
http://trac.osgeo.org/postgis/changeset/10885

**Comment by radaway** [comment]
#if PG_VERSION_NUM >= 90300
#include <access/htup_details.h>
#endif
......

static Oid
lookup_type_oid(const char *typname)
{
#if PG_VERSION_NUM >= 90300
	Oid namesp = LookupExplicitNamespace("public", false);
#else
	Oid namesp = LookupExplicitNamespace("public");
#endif
......
