### ISSUE TITLE
signal handling is not correct

### ISSUE THREAD

**Issue by okbob** [pramsey/pgsql-http#112]
I studied your code, and I don't think so SIGINT handling is correct.

You forward signal to Postgres only inside http request. But the signal handler was rewritten when library was loaded.

     load 'http';
     postgres=# select pg_sleep(100));
    ^CCancel request sent
    ^CCancel request sent
    ^CCancel request sent
   
You break cancel handling for all other functions.

**Comment by pramsey** [comment]
Good catch. Not sure I've fixed it correctly, but it does at least cancel both long running HTTP requests and long-running other requests.

**Comment by okbob** [comment]
I think it is correct
