### ISSUE TITLE
random timeouts

### ISSUE THREAD

**Issue by megamx28** [pramsey/pgsql-http#113]
I'm using this extension to do some requests to google clouds api.  99% of calls take 25ms but the other 1% of the time it times out after 5s.  I know it's not on google's end since it always fails on the first request of the function and never on any of the following during that function.

Any idea what's happening?  Is there a easy way to set retries in even of failure other than wrapping it in a function and then on excepting running it again?

**Comment by pramsey** [comment]
No idea. Do you have any examples you can share that demonstrate the behaviour?
