### ISSUE TITLE
JSON DATA

### ISSUE THREAD

**Issue by kaka2208brazill** [pramsey/pgsql-http#115]
Hi，guys！i just install u plug-in,using the http_post methods,but i found it didn't work when i post json data.Could u give me an simple JSON data example.Thanks!

**Comment by lvbuwei** [comment]
select * from http_post('http://www.xxx.com/mypost',jsonb_build_object('myuser','xxx','mypassword','xxx')::text,'application/json');

**Comment by MohamedLamineAllal** [comment]
you can use the syntax from the documentation just like this:

```sql
  select content::json->'run'->'status'
      from http_post(
          'https://aws..........',
          '''{ "projectArn": "' || run.project_arn || '", "runArn": "' || run.run_arn || '" }'',' -- payload
          'application/json'
      );
$$
```
Not that the format is

```sql
'{ "prop": "val", ... }'
```
