### ISSUE TITLE
Can't install against PostgreSQL 13

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-http#116]
This may be just my issue.  I tried compiling against PostgreSQL 13 and it compiles, but when it goes to install, it fails.
When it gets this far, it's usually a missing lib issue on my end.  Can you confirm this compiles and installs against PostgreSQL 13.

**Comment by lvbuwei** [comment]
postgre13 is No problem. I've been using it for half a year.

**Comment by robe2** [comment]
okay then it's probably something I'm missing in my dependency then like wrong version of curl loaded in my instance.  I'll close this out then.  The compiling is not the issue - it compiles fine it's the create extension that fails with can't load library or some such thing.
