### ISSUE TITLE
Local connexion refused whereas curl succeeds

### ISSUE THREAD

**Issue by GradedJestRisk** [pramsey/pgsql-http#117]
I started a [NodeJS server](https://github.com/GradedJestRisk/db-training/blob/master/RDBMS/PostgreSQL/testing/js-rpc/server.js) locally. 

curl suceeds
``` shell
curl http://localhost:3000
# Hello World!%      
```
`http_get `on the [same endpoint](https://github.com/GradedJestRisk/db-training/blob/master/RDBMS/PostgreSQL/queries/http/rpc-base.sql) fails
``` sql
SELECT hello_over_network();
#  ERROR: Failed to connect to localhost port 3000: Connection refused
```
Whereas `http_get ` succeeds on external endpoint,eg. `http://httpbin.org/get`

I tried the following:
- call `127.0.0.1` instead of `localhost`
- move the endpoint on port 80
- switch to https

I guess this is not directly related to pgsql-http, but would really help newbies :pray: 
I havent'f any related issues in [closed issues](https://github.com/pramsey/pgsql-http/issues?page=2&q=is%3Aissue+is%3Aclosed)

Configuration:
- [docker postgresql alpine 13](https://github.com/docker-library/postgres/blob/b9c080857b880202ebd23c59d33fe86d7a70fea3/13/alpine/Dockerfile)
- latest [pgsql-http](https://github.com/pramsey/pgsql-http/commit/838440662aaf6f72455ba5a4e60fcf3f3ea4229c)
- OS/Distro : Linux header 5.9.10-050910-generic  / Ubuntu 20.10

**Comment by pramsey** [comment]
Sorry, I cannot replicate and have no random guesses. If you do find the reason, please add a comment.

**Comment by nokome** [comment]
FWIW, I'm experiencing the same issue on Ubuntu 21.10. Both `localhost` an `127.0.0.1` give the error "Failed to connect to localhost port 3000: Connection refused" but if I use a local network IP address e.g. `http://192.168.8.152:3000` it succeeds.

**Comment by pramsey** [comment]
The fact that it's docker + some recent experience with containers I have had leads me to believe it might be in your container network setup. When running in some modes, containers will answers to the FQDN/IP of the host, but **not** answer to localhost. Try using the '--network=host' option when running your container.

**Comment by nokome** [comment]
Oh right yes that makes sense 🤦🏽. My `localhost:3000` is not in a container but my Postgres is (I'm using Supabase). I'll see if I can pass the `--network=host` option through to there. Thanks for the response!
