### ISSUE TITLE
Necessary data rewind wasn't possible

### ISSUE THREAD

**Issue by Tam** [pramsey/pgsql-http#119]
I'm getting `necessary data rewind wasn't possible` when trying to post any data (specifically JSON). Having an empty content string works, but adding any value triggers the error.

I've done some searching and it appears to have something to do with setting the `CURLOPT_SEEKFUNCTION`.

https://curl-library.cool.haxx.narkive.com/RqpW8H6R/issue-necessary-data-rewind-wasn-t-possible

Is there anything you can do to fix it? It doesn't seem like it's possible for me to set that value in postgres.

**Comment by pramsey** [comment]
Can you provide an example against httpbin.org that demonstrates the behaviour? Otherwise there's not much I can do. Certainly there's no reason requests should be trying to rewind.
