### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by nusret103** [pramsey/pgsql-http#12]
during the installation i am getting this error:

gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -DLINUX_OOM_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -fno-strict-aliasing -fwrapv -fpic -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o http.o http.c
http.c: In function ‘lookup_type_oid’:
http.c:204: error: too many arguments to function ‘LookupExplicitNamespace’
http.c:205: warning: implicit declaration of function ‘GetSysCacheOid2’
make: *** [http.o] Error 1

**Comment by pramsey** [comment]
What version of PostgreSQL are you compiling against? There's probably an implicit version requirement I should make explicit.

**Comment by nusret103** [comment]
I use 9.4 postgres db

**Comment by nusret103** [comment]
Hi,

It there any progress regarding the above issue.

With respect

**Comment by pramsey** [comment]
If you try compiling against 9.3 you could verify the hypothesis yourself?

**Comment by nusret103** [comment]
OS: Linux centos6.6
DB: Postgres 9.4

Is any way there how to solve this issue

**Comment by pramsey** [comment]
I just compiled against 9.4 with no issues at all, so I'm not sure what you're seeing.

**Comment by pramsey** [comment]
Actually, there is a problem compiling against 9.2. Looks like yours.

**Comment by nusret103** [comment]
Can you send me a procedure how you have installed and dependencies

**Comment by pramsey** [comment]
Type 'which pg_config' that'll tell you what pg_config is being used for your build. It's probably an old one and not the one you want. Update your PATH so that the path to your modern, pgsql 9.4 pg_config comes first (export PATH=/my/pgsql/path:$PATH)
