### ISSUE TITLE
NSS_3.34 not found

### ISSUE THREAD

**Issue by BobPao** [pramsey/pgsql-http#120]
PostgreSQL 13.1 on x86_64-pc-linux-gnu
CREATE EXTENSION http
> ERROR:  could not load library "/usr/pgsql-13/lib/http.so": /lib64/libnss3.so: version `NSS_3.34' not found (required by /lib64/libcurl.so.4)

**Comment by BobPao** [comment]
> PostgreSQL 13.1 on x86_64-pc-linux-gnu
> CREATE EXTENSION http
> 
> > ERROR:  could not load library "/usr/pgsql-13/lib/http.so": /lib64/libnss3.so: version `NSS_3.34' not found (required by /lib64/libcurl.so.4)

**Comment by TulipDi** [comment]
hi，have you solved it?
