### ISSUE TITLE
urlencode multiple parameters

### ISSUE THREAD

**Issue by olirice** [pramsey/pgsql-http#123]
Hey,

What do you think about adding a convenience wrapper to url encode multiple parameters from json/jsonb?

i.e. something like:
```sql
CREATE OR REPLACE FUNCTION urlencode(params jsonb) RETURNS text AS
$$ 
	SELECT
		'?' || string_agg(urlencode(elem::text) || '=' || urlencode(val::text), '&'::text) 
	FROM
		jsonb_each_text(params) js(elem, val)
$$ LANGUAGE SQL IMMUTABLE STRICT
```

Usage:
```sql
select
	*
from
	http_get('https://itunes.apple.com/search' || urlencode('{"term": "NPR", "limit": 10}'::jsonb))
```

Equivalent to the following:
https://docs.python-requests.org/en/master/user/quickstart/#passing-parameters-in-urls
https://www.python-httpx.org/quickstart/

**Comment by olirice** [comment]
The rationale is that if you're wrapping the call to `http_get` in a function, and the url encoded parameters are provided by that function, its clearer to template as a jsonb document rather than via string concatenation

For example:
```sql
create function search_itunes1(search_term text, max_results int default 10)
returns jsonb as
$$
	select 
		content::jsonb -> 'results'
	from http_get(
		'https://itunes.apple.com/search?term='
		|| urlencode(search_term)
		|| '&media=podcast&limit='
		|| max_results::text
		|| '&country=US'
	)
$$ language sql volatile strict;
```

is (IMO) more difficult to follow than

```sql
create or replace function search_itunes2(search_term text, max_results int default 10)
returns jsonb as
$$
	select 
		content::jsonb -> 'results'
	from http_get(
		'https://itunes.apple.com/search' ||
		urlencode(
			jsonb_build_object(
				'term', search_term,
				'media', 'podcast',
				'limit', max_results,
				'country', 'US'
			)
		)
	)
$$ language sql volatile strict;
```

In any case, if you disagree feel free to close!

Thanks for your work on this. Very cool

**Comment by pramsey** [comment]
Not at all opposed, I think you're right, just exploring the alternatives. Mostly wondering if jsonb is the easiest input path. Like what about this:
```
SELECT urlencode(ARRAY['key', 'value', 'key', value'])
```
Or the highly variadic version:
```
SELECT urlencode('key', 'value', 'key2', 'value2', 'key3', 'value3')
```
However, in a world where `jsonb_build_object()` exists, I should probably just do the json one.

**Comment by olirice** [comment]
Ah! my mistake, I misread your response

Yeah, the
```sql
SELECT urlencode('key', 'value', 'key2', 'value2', 'key3', 'value3')
```
version also looks both looks good

But I'd have a slight preference for json/b because the next thing I was going to ask about is rolling that into `http_get`

with a signature like
```sql
http_get(url text, parms jsonb)
```

**Comment by RekGRpth** [comment]
I do so in [pg_curl](https://github.com/RekGRpth/pg_curl/blob/367881d930ab35086c59eede9fc044d3e4bc3196/README.md?plain=1#L19-L24)

**Comment by pramsey** [comment]
See `http_get(url text, data jsonb)` and `http_post(url text, data jsonb)` and `urlencode(jsonb)`

**Comment by olirice** [comment]
Looks great! thank you 🙌
