### ISSUE TITLE
Are background workers used or not?

### ISSUE THREAD

**Issue by TomasHubelbauer** [pramsey/pgsql-http#127]
Hi, sorry for my confusion here, I found out about this extension through this [Supabase blog](https://supabase.com/blog/2021/03/05/postgres-as-a-cron-server). The blog states that

> # Addendum
> ## Postgres background workers
> You might have noticed this notice the warning at the bottom of the http readme:
> > "What happens if the web page takes a long time to return?" Your SQL call will just wait there until it does. Make sure your web service fails fast.
> 
> Luckily pg_cron implements Background Workers:
> > Care is taken that these extra processes do not interfere with other postmaster tasks: only one such process is started on each ServerLoop iteration. This means a large number of them could be waiting to be started up and postmaster is still able to quickly service external connection requests.
> 
> This means that even if your endpoint takes a long time to return, it's not going to be blocking your core Postgres functions. Either way, you should probably only call endpoints that will return a response quickly, or set the http extension to fail fast (`http.timeout_msec = 300`).

I do see the first quote in the readme, but I couldn't find the second one. The blog seems to imply `pgsql-http` is already using background workers, so the invocation of the HTTP connection will not block the database over the course of its duration.

However, in the readme, among the listed to-do items, I see

> The new http://www.postgresql.org/docs/9.3/static/bgworker.html background worker support could be used to set up an HTTP request queue, so that pgsql-http can register a request and callback and then return immediately.

This to me reads as though background workers are not being used? Could you please clarify?

- If background workers are being used, may I PR the readme to remove the obsolete todo?
- If not, does the execution of the HTTP communication block the database / lock the table while it is ongoing?
  - If so, may I PR the readme to reword "Your SQL call will just wait there until it does. Make sure your web service fails fast." to more clearly state the scope of the blockage? To explicitly mentioned the database is unavailable for writes/reads during the execution, or the cron queue is blocked or whichever happens to be the case, please clarify.
  - If it does not, how is that achieved without background workers? Does cURL run in a separate process / is the libcurl call async and a callback is used to populate the database after the HTTP call ends?
  - I will contact Supabase about updating the blog post to accurately state background worker support in this case.

Thanks for entertaining my questions!

**Comment by pramsey** [comment]
Background workers are not used. pgsql-http is 100% synchronous. In terms of blocking/locking, I have not experimented, but I'd expect the same level of locking you'd see with any other MVCC query, which is not too intrusive **usually** but will last for the (quite long, in database terms) duration of the query. Certainly the one backend running the query is fully blocked until it's done, but I don't think that will block other backends from going about their business, particularly if you're doing a query which doesn't involve writing.
Anything you discover, yes, a PR to clarify would always be welcomed.

**Comment by TomasHubelbauer** [comment]
Thank you for the answers. I'll try to get the Supabase blog updated. I though about how this project's readme could be updated. My initial wonder filing this issue was whether I should still be able to read from the database as the network call is ongoing. Seems like that is the case, but I'm not coming up with anything good to update the readme with over what it already has, so I'll leave it alone.
