### ISSUE TITLE
CURLOPT_USERPWD  and example uses

### ISSUE THREAD

**Issue by sysadminmike** [pramsey/pgsql-http#129]
I have added:

    { "CURLOPT_USERPWD", NULL, CURLOPT_USERPWD, CURLOPT_STRING, false },

Compiled and tested with no problems - could you please add to the list of options when you next work on this project

Thanks.

I have found this extension very useful and have documented some uses:

https://github.com/sysadminmike/pgsql-http_examples

**Comment by pramsey** [comment]
Done at e7b016ad18ab2b6ace4c1d3208fc2901a20d9efa
