### ISSUE TITLE
ERROR:  cache lookup failed for type 0

### ISSUE THREAD

**Issue by arakattack** [pramsey/pgsql-http#13]
Hi,

This is very cool idea but I got difficulties using this library.
Compiling is no problem on CentOS 5.8 with pg 9.1.15
But create extension failed with various errors (not found module path, type column). Having successfully installed extension, I couldn't use it due to ERROR: cache lookup failed for type 0
Only urlencode() works.

Please advise.
Thank you

PS: I edited sql with code below:

CREATE DOMAIN http_method AS text
CHECK (
    VALUE ILIKE 'get' OR
    VALUE ILIKE 'post' OR
    VALUE ILIKE 'put' OR
    VALUE ILIKE 'delete'
);

CREATE DOMAIN content_type AS text
CHECK (
    VALUE ~ '^\S+\/\S+'
);

CREATE TYPE http_header AS (
    field VARCHAR,
    value VARCHAR
);

CREATE TYPE http_response AS (
	status INTEGER,
	content_type VARCHAR,
	headers http_header[],
	content VARCHAR
);

CREATE TYPE http_request AS (
	method http_method,
    uri VARCHAR,
	headers http_header[],
	content_type VARCHAR,
	content VARCHAR
);

CREATE OR REPLACE FUNCTION http_header (field VARCHAR, value VARCHAR) 
    RETURNS http_header
    AS $$ SELECT $1, $2 $$ 
    LANGUAGE 'sql';

CREATE OR REPLACE FUNCTION http(request http_request)
    RETURNS http_response
    AS '$libdir/http', 'http_request'
    LANGUAGE 'c';

CREATE OR REPLACE FUNCTION http_get(uri VARCHAR)
	RETURNS http_response
	AS $$ SELECT http(('GET', $1, NULL, NULL, NULL)::http_request) $$
    LANGUAGE 'sql';

CREATE OR REPLACE FUNCTION http_post(uri VARCHAR, content VARCHAR, content_type VARCHAR)
	RETURNS http_response
	AS $$ SELECT http(('POST', $1, NULL, $3, $2)::http_request) $$
    LANGUAGE 'sql';

CREATE OR REPLACE FUNCTION http_put(uri VARCHAR, content VARCHAR, content_type VARCHAR)
	RETURNS http_response
	AS $$ SELECT http(('PUT', $1, NULL, $3, $2)::http_request) $$
    LANGUAGE 'sql';

CREATE OR REPLACE FUNCTION http_delete(uri VARCHAR)
	RETURNS http_response
	AS $$ SELECT http(('DELETE', $1, NULL, NULL, NULL)::http_request) $$
    LANGUAGE 'sql';

CREATE OR REPLACE FUNCTION urlencode(string VARCHAR)
	RETURNS TEXT
	AS '$libdir/http'
	LANGUAGE 'c'
	IMMUTABLE STRICT;

**Comment by pramsey** [comment]
Can you tell me what you changed?

**Comment by arakattack** [comment]
Hi Paul,

I modified the function parameters into  $1, $2, $3.
And I hardcoded $libdir/http
