### ISSUE TITLE
Get a svg image from http.get

### ISSUE THREAD

**Issue by Danilo-MSI** [pramsey/pgsql-http#131]
Hello to you all! I hope everyone is doing fine!

Anyway, from the http.get function, I can get a JPEG, GIF and PNG image no problem. But, when it is a svg image all I can get is the xml code (if I can call it that). And not only that, but the "where" clause don't find any field with 'Content-Length' . For exemple, with this code:

WITH
  http AS (
    SELECT * FROM http_get('https://c2.scryfall.com/file/scryfall-symbols/card-symbols/T.svg')
  ),
  headers AS (
    SELECT (unnest(headers)).* FROM http
  )
SELECT
  http.content_type,
  length(textsend(http.content)) AS length_binary,
  textsend(http.content) AS image,
  headers.value AS length_headers
FROM http, headers
WHERE field = 'Content-Length';

But even if I remove the "where" clause, I only get the <svg xmlns> code retuning in the "image" field ("textsend" function) There is a way that I can get the bytea from the svg uri using, who knows, another function or some other way, maybe?

Returning from image = ' <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><g transform='translate(0 -1)' fill='none'><circle fill='#CAC5C0' cx='50' cy='50.998' r='50'/><path d='M85.332 59.918h-36.004l13.185-9.383c-4.898-3.887-10.566-5.828-16.984-5.828-3.211 0-5.414.613-6.59 1.836-1.184 1.227-1.777 3.445-1.777 6.654 0 8.873 4.563 18.34 13.691 28.396l-10.391 10.521c-12.09-14.705-18.129-27.844-18.129-39.424 0-6.928 2.086-12.447 6.27-16.545 4.18-4.098 9.746-6.148 16.668-6.148 8.453 0 17.664 3.215 27.641 9.635l7.728-13.182 4.692 33.468z' fill='#0D0F0F'/></g></svg> '

Thanks to you all!

**Comment by Danilo-MSI** [comment]
>

**Comment by pramsey** [comment]
Is it possible you are over-thinking this? The SVG is just text, so you don't need to do anything special to see it, just look at http.content. Works fine for me!
```sql
SELECT content FROM http_get('https://c2.scryfall.com/file/scryfall-symbols/card-symbols/T.svg');
```
```                                                                                                                                                                                                                                                                                  <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><g transform='translate(0 -1)' fill='none'><circle fill='#CAC5C0' cx='50' cy='50.998' r='50'/><path d='M85.332 59.918h-36.004l13.185-9.383c-4.898-3.887-10.566-5.828-16.984-5.828-3.211 0-5.414.613-6.59 1.836-1.184 1.227-1.777 3.445-1.777 6.654 0 8.873 4.563 18.34 13.691 28.396l-10.391 10.521c-12.09-14.705-18.129-27.844-18.129-39.424 0-6.928 2.086-12.447 6.27-16.545 4.18-4.098 9.746-6.148 16.668-6.148 8.453 0 17.664 3.215 27.641 9.635l7.728-13.182 4.692 33.468z' fill='#0D0F0F'/></g></svg>+
```
