### ISSUE TITLE
SQL Error [XX000]: ERROR: "A libcurl function was given a bad argument" after upgrade from Centos 7.7 to 7.9

### ISSUE THREAD

**Issue by javierordonezojeda** [pramsey/pgsql-http#142]
After upgrading from Centos 7.7 to 7.9, when trying to execute the "http" function, the following error appears:

SQL Error [XX000]: ERROR: "A libcurl function was given a bad argument"

Centos 7.7 -> curl 7.79.1
Centos 7.9 -> curl 7.84.0

**Comment by pramsey** [comment]
Sounds like the Centos packager didn't update the pgsql-http extension when the curl library was incremented. Nothing much I can do here, it's a packaging / installation issue. Build from source, it'll work fine I bet.
