### ISSUE TITLE
Support OAuth2

### ISSUE THREAD

**Issue by yan-hic** [pramsey/pgsql-http#149]
I thought of using the wrapper to call a authenticated endpoint at GCP (Cloud Run service) but I am not clear on how to create the token, if even possible, to use in OAuth2 calls. As a reference, G detailed the steps [here](https://cloud.google.com/functions/docs/securing/authenticating#exchanging_a_self-signed_jwt_for_a_google-signed_id_token).

@pramsey can you may be add an example on how-to, including how to generate a JWT from within PG ? Or wrap the functionality in the wrapper itself.
 
This is obviously not GCP-specific.

**Comment by pramsey** [comment]
I would welcome a good PR for that doco, but I don't really have the bandwidth to research up an answer for you.

**Comment by yan-hic** [comment]
Understand - I thought you may know how, and not just for me. Maybe using https://github.com/michelp/pgjwt helps but I lack the expertise. Will try to reach out to Googlers to see how-to authenticate using only `curl`, and test the same using this lib.
