### ISSUE TITLE
Issue under PostgreSQL 9.4 (Server is version 9.4, library is version 9.3.)

### ISSUE THREAD

**Issue by jacobpasterkamp** [pramsey/pgsql-http#15]
I tried to install the extension under PostgreSQL 9.4, but i get the following message :

ERROR:  incompatible library "/usr/pgsql-9.4/lib/http.so": version mismatch
DETAIL:  Server is version 9.4, library is version 9.3.
********** Error **********

ERROR: incompatible library "/usr/pgsql-9.4/lib/http.so": version mismatch
SQL state: XX000
Detail: Server is version 9.4, library is version 9.3.

is it possible to fix this?

**Comment by pramsey** [comment]
You need to rebuild the source against 9.4, you cannot use a 9.3 binary against 9.4.

**Comment by jacobpasterkamp** [comment]
I do rebuild (make) the sources with 9.4 on the make command i get the following result, is that correct? :

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -I/usr/include/et -fpic -shared -o http.so http.o stringbuffer.o -L/usr/pgsql-9.4/lib -L/usr/lib64 -Wl,--as-needed  -lcurl

**Comment by pramsey** [comment]
Look right. Then `make install`. And check that the `pg_config` on your path is actually the one from 9.4 `pg_config --version`

**Comment by jacobpasterkamp** [comment]
Sorry to bother you. the issue is FIXED.
I was using an older version of your sources (working on an offline server...).
 I dowloaded the latest version and now it works. :+1: 
Thanks for the fast responses!

**Comment by jacobpasterkamp** [comment]
the output was also al little bit different :

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -I/usr/include/et -fpic -I. -I./ -I/usr/pgsql-9.4/include/server -I/usr/pgsql-9.4/include/internal -I/usr/include/et -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o http.o http.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -I/usr/include/et -fpic -shared -o http.so http.o -L/usr/pgsql-9.4/lib -L/usr/lib64 -Wl,--as-needed  -lcurl
