### ISSUE TITLE
send a header along with the post request

### ISSUE THREAD

**Issue by haowuge** [pramsey/pgsql-http#154]
Hello, I need to send a header along with the post request, but I found that the "public"."http_post" function hardcodes the headers field, is there any special reason for this? 
How do I proceed in this case? 

I tested "public"."http" and it works fine

Thank you!

`SELECT public.http(('POST', 'http://github.com/api', ARRAY[http_header('User-Agent','BotAgent'),http_header('Authorization','bearer ey***************M8s')], 'application/json'::text, '{"A": "B","C": "D"}')::public.http_request) `

**Comment by pramsey** [comment]
The "specific requests" signatures are designed to lower the number of options and capabilities, with the generic http signature to handle all the people with extra needs, so this is by design.
