### ISSUE TITLE
[XX000] ERROR: pgsql-http requires Curl version 0.7.20 or higher

### ISSUE THREAD

**Issue by jacobpasterkamp** [pramsey/pgsql-http#16]
Hi,

I was able to get pgsql-http installed under PostgreSQL 9.4 (Redhat 6.6)

But now when i execute the function http_post() i get :

[XX000] ERROR: pgsql-http requires Curl version 0.7.20 or higher

Initially i had curl 7.19 installed, but this messages keeps coming even after i upgraded to curl 7.31
Also i did rebuild the sources after upgrading curl to 7.31

**Comment by pramsey** [comment]
You installed a new version of curl, but you didn't get rid of the old one, it's still on your system and pgsql-http is still linking to it. Depending on your system you have to figure a way to get the linker to prefer the new library to the old one.

**Comment by NathakornJ** [comment]
Hi, 
I am trying to sync data between postgresql and couchdb. I am facing exactly the same problem as reported by jacobpasterkamp. I would like to know if this issue has been resolved, or pramsey, please can you advise with more details what I have to do in order to get the linker work correctly.

**Comment by pramsey** [comment]
Sorry, this is sysadmin support stuff, not developer support. Use your OS tools like `find` and `locate` to track down copies of libcurl and get rid of the old ones (preferably using your package manager, not blunt instruments like `rm -f`).

**Comment by NathakornJ** [comment]
Hi, Paul Ramsey,
Thanks. I installed the latest version of curl and libcurl packages from  city fan repo. This issue has been resolved.
