### ISSUE TITLE
CURLOPT_DNS_SERVERS "An unknown option was passed in to libcurl"

### ISSUE THREAD

**Issue by mazniak** [pramsey/pgsql-http#169]
The CURLOPT_DNS_SERVERS options seems completely broken currently. I'm running a supabase local container which has libcurl 7.68.0 installed and I cannot seem to use this config.

```sql
SELECT http_set_curlopt('CURLOPT_DNS_SERVERS', '127.0.0.1');
-- ERROR:  An unknown option was passed in to libcurl
```

meanwhile 

```sql
SELECT * FROM http_list_curlopt();
```

returns 

```
+-----------------------+--------------+
|     curlopt           |   value      |
+-----------------------+--------------+
| CURLOPT_DNS_SERVERS   | 127.0.0.1    |
+-----------------------+--------------+
```

**Comment by pramsey** [comment]
Hm, no way to fix this on our end... 

https://curl.se/libcurl/c/CURLOPT_DNS_SERVERS.html

"This option requires that libcurl was built with a resolver backend that supports this operation. The c-ares backend is the only such one."

The curl you are running against must not have been built with this option. (Mine hasn't either.)

**Comment by mazniak** [comment]
Ah thank you!
