### ISSUE TITLE
do I have to create this types or is the create extention doing this

### ISSUE THREAD

**Issue by walpino** [pramsey/pgsql-http#17]
SELECT ext.http_get('www.google.com'
);

ERROR:  type "http_request" does not exist
LINE 1:  SELECT http(('GET', $1, NULL, NULL, NULL)::http_request) 
                                                    ^
QUERY:   SELECT http(('GET', $1, NULL, NULL, NULL)::http_request) 
CONTEXT:  SQL function "http_get" during inlining
********** Fehler **********

ERROR: type "http_request" does not exist
SQL Status:42704
Kontext:SQL function "http_get" during inlining

**Comment by pramsey** [comment]
CREATE EXTENSION should be creating the type as well as the functions.

**Comment by walpino** [comment]
so I guess I found out 
I have a specific schema for extension  and it is not in public schema

is this a problem?

**Comment by pramsey** [comment]
Does adding your schema to the search_path fix the problem? I feel like there's some magic I can add to my .sql file to make your problem go away in general though, will do some research.

**Comment by walpino** [comment]
Hi 

I altered the search_path to schema1, ext 

but the same error

**Comment by pramsey** [comment]
Funny, that change works for me. 

 create extension http schema http;
 set search_path = public,http;
 select http_get('http://localhost');

**Comment by walpino** [comment]
ah you mean to set the search_path to the public as well 
I though to set it to the user_schema, extention_schema

I'm not sure if we will drop the public schema later so we wouldn't have a public schema

so the to types are generated always in the public schema ? not in the schema where I create the extention?

**Comment by pramsey** [comment]
No, I just include `public` as a habit, but it's not required either,
```sql
create extension http schema http;
set search_path = http;
select http_get('http://localhost');
```
