### ISSUE TITLE
return "content" as bytea

### ISSUE THREAD

**Issue by PaulVladescu** [pramsey/pgsql-http#172]
"To access binary content, you must coerce the content from the default varchar representation to a bytea representation using the text_to_bytea function. Using the default varchar::bytea cast will not work, as the cast will stop the first time it hits a zero-valued byte (common in binary data).
"
Composite type "public.http_response"
    Column    |       Type        | Modifiers
--------------+-------------------+-----------
 status       | integer           |
 content_type | character varying |
 headers      | http_header[]     |
 content      | character varying |

Why not returning the "content" as bytea

**Comment by pramsey** [comment]
Because then we have the reverse inconvenience for people who just want strings.

**Comment by pramsey** [comment]
To convert from text to bytea you have to tell the system how the high bits are encoded in the text string. Usually people are just converting plain ASCII7 text, and `decode('the text string', 'escape)` works fine for that.

**Comment by PaulVladescu** [comment]
In "public.http_response.content" there is the binary content of a pdf file, decode is not useful.

**Comment by PaulVladescu** [comment]
I was looking for this function "text_to_bytea" first thing after reading your documentation, but I couldn't find it. Maybe I just missed it. If you know about it please tell me where to find it.

**Comment by PaulVladescu** [comment]
I updated to http version 1.6 and the function  text_to_bytea is present.
It also works with textsend.

Thank you very much
