### ISSUE TITLE
ERROR:  HTTP request cancelled

### ISSUE THREAD

**Issue by peterfutaro** [pramsey/pgsql-http#173]
Hi there,

I use pgsql-http in my stored procedure.
During with my testing just now, my procedure was stopped and I got that error (ERROR: HTTP request cancelled) after the procedure ran for 1 minute (exactly stopped at 00:01:00) and after calling around 55 http requests.

Can you please tell me if this is because of the limit in pgsql-http ?
And if so, what is the best pratcice to handle my scenario ?

Thank you

**Comment by pramsey** [comment]
No idea. There's a timeout set for a *single* http call, but there's no reason a loop around http calls should stop after one minute from an http point of view. From a database point of view though, your one function is in one transaction, and it's probably hitting your PostgreSQL statement_timeout limit?
