### ISSUE TITLE
possible issue with PUT

### ISSUE THREAD

**Issue by sysadminmike** [pramsey/pgsql-http#20]
Hi,

I think there may be an issue with PUT requests please see:

https://github.com/sysadminmike/couch-to-postgres/issues/21

I have done some further testing and get an error as well but not a postgres crash
For example if i run:

```
SELECT status FROM http_put('http://192.168.3.21:5984/newdb'::text, ''::text, 'application/json'::text); 
```

This returns correctly (note this creates a db on couchdb).

If i then add some content to the request to make a document in couch:

```
SELECT status FROM http_put('http://192.168.3.21:5984/newdb/puttest-1'::text, '{"myvar":1}'::text, 'application/json'::text); 
```

In postgres log i see:

```
Oct  5 11:06:17 postgres postgres[95749]: [8-1] ERROR:  select/poll returned error
Oct  5 11:06:17 postgres postgres[95749]: [8-2] STATEMENT:  
Oct  5 11:06:17 postgres postgres[95749]: [8-5]     SELECT status FROM http_put('http://192.168.3.21:5984/newdb/puttest-1'::text, '{"myvar":1}'::text, 'application/json'::text); 
```

And in pgsql i get back 

```
ERROR:  select/poll returned error
********** Error **********

ERROR: select/poll returned error
SQL state: XX000
```

If i try to run the request as a POST then all is ok

```
SELECT status FROM http_post('http://192.168.3.21:5984/newdb'::text, '{"_id":"posttest-1"}'::text, 'application/json'::text); 
```

**Comment by pramsey** [comment]
I'm seeing put working fine on my tests

    select * from http_put('https://httpbin.org/put?foo=bar', 'some text', 'text/plain');
