### ISSUE TITLE
ERROR:  Operation timed out after 0 milliseconds with 0 out of 0 bytes received WHEN doing post request

### ISSUE THREAD

**Issue by aleksandrmelnyk** [pramsey/pgsql-http#23]
am trying to post request like following:

```
SELECT status, "content" INTO v_response_code, v_response_content
      FROM http_post(v_redmine_url||'/issues.json'||urlencode('?key='||v_redmine_api_key),
                     format('{"issue": {"project_id": %s, "subject": "%s", "status_id": %s, "description": %s, "tracker_id": }}', v_redmine_project, NEW.id, v_new_status_id, v_subject||' '||v_description, v_crossings_tracker_id),
                     'application/json');
```

and getting error:
_ERROR:  Operation timed out after 0 milliseconds with 0 out of 0 bytes received
CONTEXT:  SQL statement "SELECT status, "content"                                                FROM http_post(v_redmine_url||'/issues.json'||urlencode('?key='||v_redmine_api_key),
                     format('{"issue": {"project_id": %s, "subject": "%s", "status_id": %s, "description": %s, "tracker_id": }}', v_redmine_project, NEW.id, v_new_status_id, v_subject||' '||v_description, v_crossings_tracker_id),
                     'application/json')"_

**Comment by mamayoleksandr** [comment]
PostgreSQL 9.4.6 on x86_64-suse-linux-gnu, compiled by gcc (SUSE Linux) 4.8.5, 64-bit

curl 7.37.0 (x86_64-suse-linux-gnu) libcurl/7.37.0 OpenSSL/1.0.1i zlib/1.2.8 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp

**Comment by mamayoleksandr** [comment]
may be it is due to using SSL. Does it support SSL?

**Comment by pramsey** [comment]
I would expect it to work transparently as long as Curl has SSL compiled. Try hitting a known working SSL URL and see.
