### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by jotpe** [pramsey/pgsql-http#24]
Great extension! That's exactly what I was searching for.

Does this extension work with a proxy?
Can a special CA file be used?

Best regards
Johannes

**Comment by pramsey** [comment]
For now, I think by laying the information you want into the environment variables you start up PostgreSQL with: https://curl.haxx.se/docs/manpage.html#ENVIRONMENT

I haven't thought much about what a clean configuration of such things might be for the extension. GUC variables? Yet More Parameters? A JSONB parameter object?

**Comment by jotpe** [comment]
I the meanwhile I implemented it with guc. I think guc is not bad for general runtime configuration of an extension.

**Comment by jotpe** [comment]
I think there are problems with http_proxy settings though an environment variable. I guess it is not always possible to bind this variable to the sql session (JDBC?). With guc, you won't have any restrictions to set this setting through normal sql statements.

Why not wrapping libcurl options to this extension only when user needs it?

You may have a look at pull request #25 .

**Comment by pramsey** [comment]
GUCs in extensions have caused me quite a bit of pain in the past, though in a non-persistent extension like this one, perhaps they wouldn't be so bad. More problematic is the restricted nature: one for proxy, one for this, one for that. There's so many potential options to set! I feel like a key/value approach w/ json might be better.

**Comment by pramsey** [comment]
See #44 for a maybe solution?
