### ISSUE TITLE
pgsql-http build broken for Postgres 9.5

### ISSUE THREAD

**Issue by juliogonzalez** [pramsey/pgsql-http#28]
It seems that it's not possible to build pgsql-http for Postgres 9.5 (at least for current 9.5.3) because of changes at PostgreSQL public functions:
```
+ make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_ADJ=0 -fpic -I. -I./ -I/usr/pgsql-9.5/include/server -I/usr/pgsql-9.5/include/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o http.o http.c
http.c: In function 'header_array_to_slist':
http.c:235:2: error: too few arguments to function 'array_create_iterator'
  iterator = array_create_iterator(array, 0);
  ^
In file included from http.c:46:0:
/usr/pgsql-9.5/include/server/utils/array.h:448:22: note: declared here
 extern ArrayIterator array_create_iterator(ArrayType *arr, int slice_ndim, ArrayMetaState *mstate);
```

**Comment by pramsey** [comment]
I'm not seeing this. You are building from git master? You have this line in your source?

https://github.com/pramsey/pgsql-http/blob/ddf660b6e382e5574da134c4cdc52556c6044c72/http.c#L272-L276

On the one hand, you have include paths to 9.5. On the other hand, the `#define PG_VERSION_NUM >= 90500` test seems to be failing. Maybe you also have some headers from an older version lying around your environment? Check that you don't have a `postgres.h` file somewhere other than your 9.5 source tree, particularly in a global slot like `/usr/include`

**Comment by juliogonzalez** [comment]
I was using the last stable release (1.1.1) which is 6 commits behind master, and that was the problem.

Other than, yes, I was including the headers, and I'm building on a fresh docker instance.

In fact I'm creating a SPEC to generate RPMs at: https://github.com/juliogonzalez/pgsql-http-rpm so in the end the way of building is:
```
PATH=/usr/pgsql-9.4/bin:$PATH make
```
(this is from the 9.4 SPEC as in the time being I deleted the SPEC file for 9.5, as it was not working).

I'll readd 9.5 support as soon as there's a new release (1.2 maybe?)

Please, feel free to close the issue, and sorry about the inconvenience :-)
