### ISSUE TITLE
http_post Error with Certificate

### ISSUE THREAD

**Issue by walpino** [pramsey/pgsql-http#29]
Hi we want to use you extensions to make an http_post request

but we get an 
ERROR:  Peer's Certificate issuer is not recognized.

on the Shell with Curl there is an Option -k to supress this Error

is it possible to do it with you extention as well?

Thanks

**Comment by pramsey** [comment]
No, it is not. There's about a [million options](https://curl.haxx.se/libcurl/c/curl_easy_setopt.html) for curl, and right now no generic way to support them. Hopefully will have one to help all you folks some day. It's easy enough to go in an monkey patch in some hardcoded values and then re-build for your particular environment, if it comes to that.

**Comment by walpino** [comment]
okay that means that curl calls like 

curl --form 'image=@Pictures/Fireman-Sam-image.jpg' --form 'app_id=adfadf' --form 'action=upload_image' --form 'hash=f55d717f45391971d8286522eac077e7fb0d52a1' https://www2.dd.scmdddev.ch/api/newad.json
{ "newad": { "image_id": "0935300038.jpg", "status": "OK"} }

are not possible as well?

**Comment by pramsey** [comment]
no, you should be able to create a form url-encoded payload and use a post operation to send that, see the doco...

**Comment by pramsey** [comment]
For support for odd curl options, see #44.
