### ISSUE TITLE
Fetching Binary Data

### ISSUE THREAD

**Issue by kjurka** [pramsey/pgsql-http#3]
The fact that http_get returns varchar prevents this from being used to return binary data.  I was specifically trying to fetch some images from a webserver.

**Comment by mclei-asw** [comment]
This recommendation does not work, when client charset is different from database charset. For example, when my database charset is UTF-8 and client charset is WINDOWS-1250, then I get error about conversion:
`ERROR:  invalid byte sequence for encoding "UTF8": 0xe2 0xe3 0xcf`

I have solved it be force defining **SET client_encoding = 'UTF8'** for the function, which calls the http_post:
```
create or replace function test (
  in URL text,
  in RequestData text,
  in ContentType text
)  returns test_rs
language plpgsql SET client_encoding = 'UTF8' as $$
declare
  l_Result                 test_rs;
begin
  select status, content_type, textsend(content) into l_Result.STATUS, l_Result.CONTENTTYPE, l_Result.CONTENT
    from public.http_post(URL, RequestData, ContentType);
  return l_Result;
end; $$;
```
