### ISSUE TITLE
Alternate 'http_header' relation on search_path crashes backend

### ISSUE THREAD

**Issue by jotpe** [pramsey/pgsql-http#30]
The server process always shuts down when executing this statement: 
```sql
select http_get('http://nominatim.openstreetmap.org/reverse.php?format=json&lat=50.9318&lon=6.9679');
```
SSL-SYSCALL-Fehler: Dateiende entdeckt
Die Verbindung zum Server wurde verloren.  Versuche Reset: Fehlgeschlagen.

postresql logfile:

> LOG:  Serverprozess (PID 2274) wurde von Signal 11 beendet: Segmentation fault
> DETAIL:  Der fehlgeschlagene Prozess führte aus: select http_get('http://nominat
> im.openstreetmap.org/reverse.php?format=json&lat=50.9318&lon=6.9679');
> LOG:  aktive Serverprozesse werden abgebrochen
> WARNUNG:  breche Verbindung ab wegen Absturz eines anderen Serverprozesses
> DETAIL:  Der Postmaster hat diesen Serverprozess angewiesen, die aktuelle Transaktion zurückzurollen und die Sitzung zu beenden, weil ein anderer Serverprozess abnormal beendet wurde und möglicherweise das Shared Memory verfälscht hat.
> TIPP:  In einem Moment sollten Sie wieder mit der Datenbank verbinden und Ihren Befehl wiederholen können.

What is the problem? Invoking curl directly with this url works fine.

**Comment by pramsey** [comment]
Not sure, something is crashing it. Testing myself, I do not have any problems, it successfully retrieves the result from nominatum. So, what version of PgSQL are you on? Was your version of http compiled against that same version, or are you using a copy of the http.so compiled against a different version? That's all I have for guesses.

**Comment by jotpe** [comment]
Im using postgreSQL 9.4 and its dev-packages. I compiled the latest version of your module.

Cannot reproduce this error after I recreated the extension and reinstalled the binary (which was not rebuild). Now it works... Hm.

**Comment by jotpe** [comment]
As superuser no error occurs, but as normal user.

**Comment by pramsey** [comment]
No problems for me with normal user either.

**Comment by jotpe** [comment]
The normal user has a view called http_header in the search_path before the extension schema. Without that view, no error occurs.

**Comment by pramsey** [comment]
We've got a winner. That (having another definition for http_header getting in front of the extension one) nicely crashes things....
