### ISSUE TITLE
HTTP_POST - Timeout error  for large volume of data

### ISSUE THREAD

**Issue by mmamajiwala** [pramsey/pgsql-http#33]
Hello,

We are getting http timeout error while posting large volume of data via http_post postgres db package.

ERROR:  Operation timed out after 5001 milliseconds with 0 bytes received
CONTEXT:  SQL statement "SELECT status, content                         FROM http_post(v_httpurl,v_jsondata,'application/json; charset=utf8')"

It works perfectly fine for small set of data. If we are sending huge volume of data, we are getting Timeout error.  Any help on this would be highly appreciated.

Do we need to set any parameters at DB or System level. Please advice.

Thanks in advance.

Mohammad Mamajiwala

**Comment by mmamajiwala** [comment]
We are using Postgres version 9.3.4 running on Amazon AWS EC2 instance. We have already tried SET and SET LOCAL, or even modifying postgresql.conf but no luck for this timeout error. 

As per wiki page we have tried to set this parameter http.timeout_msec to solve timeout error but we are getting same issue.

**Comment by juliogonzalez** [comment]
So finally the problem here was that the http.timeout_msec was added after version 1.1.1 (which is the last stable).

After using the last commit from master, it is working.

**Comment by pramsey** [comment]
Aha. I published a new 1.1.2 release so other folks don't get burned by the same thing. The ease of running a trunk on github is making me lazy on releases.
