### ISSUE TITLE
SSL Certificate do https

### ISSUE THREAD

**Issue by fgracalepsus** [pramsey/pgsql-http#36]
I'm having the follow message on url bellow:
"ERROR:  SSL certificate problem: unable to get local issuer certificate"

Query:
select * FROM http_get('https://maps.googleapis.com/maps/api/geocode/json?address=')

When expected result is:
"{
   "error_message" : "Invalid request. Missing the 'address', 'bounds', 'components', 'latlng' or 'place_id' parameter.",
   "results" : [],
   "status" : "INVALID_REQUEST"
}"

**Comment by pramsey** [comment]
Works for me. Probably something is amiss in your libcurl or your libssl installations. I found that both a commandline hit and a pgsql-http hit worked fine

    curl "https://maps.googleapis.com/maps/api/geocode/json?address="

**Comment by Skullcan** [comment]
Sorry for reopening this issue, but i can't do a https request also.

command line works fine for me:
```
C:\Windows\system32>curl "https://maps.googleapis.com/maps/api/geocode/json?addr
ess="
{
   "error_message" : "Invalid request. Missing the 'address', 'bounds', 'compone
nts', 'latlng' or 'place_id' parameter.",
   "results" : [],
   "status" : "INVALID_REQUEST"
}
```

But http_post() returns:
```
select * from http_get('https://portal.emif.com.br/EmifPushApp/api/usuarios');

ERROR:  SSL certificate problem: unable to get local issuer certificate
********** Error **********

ERROR: SSL certificate problem: unable to get local issuer certificate
SQL state: XX000
```
Running Windows Version on Postgre 9.4.

Am missing something? Thank you!

**Comment by fgracalepsus** [comment]
I jump to red hat to solve my problem.

In windows, problems persists.

[]'s

Att,


2017-02-07 9:36 GMT-02:00 Skullcan <notifications@github.com>:

**Comment by Skullcan** [comment]
Sadly that's not an option for me :(
