### ISSUE TITLE
Ability to override the CAInfo so don't get ERROR:  SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-http#38]
This is probably more of an issue on Windows EDB version.  On BigSQL windows version surprisingly it's not so much of an issue.

Regarding where I place the cabundle.crt file, it never is found.  Doing a process file check, , it never ieven seems to try to look for it.

That said, I can't get https to work at all under PostgreSQL VC++ builds without being able to set the CURL_CAINFO.

so things like:

`
SELECT * FROM http_get('https://www.google.com');

ERROR:  SSL certificate problem: unable to get local issuer certificate
********** Error **********
`

I have a patch which I'll send shortly to add another GUC http.cainfo.  Feel free to reject it since I know you don't want to add any other specific GUCs.

**Comment by robe2** [comment]
pull request here: https://github.com/pramsey/pgsql-http/pull/39

**Comment by pramsey** [comment]
Check out #44.
