### ISSUE TITLE
Throttle requests?

### ISSUE THREAD

**Issue by chriszrc** [pramsey/pgsql-http#41]
For an operation like geocoding, not every site is going to like getting hammered with lots of requests. Is there currently any way to throttle requests that are made, say by 50 or 100 milliseconds? And if not, I think this would be a really useful improvement-

**Comment by calz1** [comment]
I had a similar problem and just put pg_sleep() calls in between calls to http().

**Comment by chriszrc** [comment]
Nice, I'm new to pl/pgsql, just came across pg_sleep(), yeah that looks perfect, thanks!
