### ISSUE TITLE
Is this available to PGXN?

### ISSUE THREAD

**Issue by gianluca-nitti** [pramsey/pgsql-http#43]
I'm not sure whether this extension is available on [PGXN](https://pgxn.org), I see that there is a [META.json](https://github.com/pramsey/pgsql-http/blob/master/META.json) file containing PGXN metadata, but I can't find pgsql-http on PGXN neither by going to https://pgxn.org/dist/http/ (where in my understanding should be according to the `"name": "http"` entry in the metadata file) nor by using PGXN's search engine.

If it isn't published, are there any plans to publish it (given the presence of the metadata file)?

Thank you and sorry if this a dummy question/not a real issue but I don't understand why there is a META.json and I can't find the page on the PGXN site, maybe it's me not searching in the correct way.

**Comment by pramsey** [comment]
No, I have no plans to publish. Would be nice if I could just throw a github URL at pgxn and have it find all the things it wants. Or at least throwing it a URL to the github .zip link.

**Comment by gianluca-nitti** [comment]
Okay, thank you for the clarification.
