### ISSUE TITLE
ERROR:  Connection timed out after 1001 milliseconds

### ISSUE THREAD

**Issue by fluancefg** [pramsey/pgsql-http#46]
Hi,
I get this error message randomly when I try to issue the following query:

`SELECT content FROM http_get('https://www.mysite/FR/data/123456-7890')`

Of course, the timeout may vary for few milliseconds.
What's weird is I read that CURLOPT_CONNECTTIMEOUT is set to 300s by default. And I can't modify this value anyway.
And I have checked the value of http.timeout_msec which is set to 5s:

`show http.timeout_msec ;`
`http.timeout_msec `
`-------------------`
 `5s`

So basicaly, I don't understand where does this 1000 ms limit come from.
Thanks

**Comment by fluancefg** [comment]
Ok, I've found the following line in the http.c:
`CURL_SETOPT(g_http_handle, CURLOPT_CONNECTTIMEOUT, 1);`

So it seems it's hardcoded and not allowed to be changed at runtime.

**Comment by fluancefg** [comment]
Ok, so for the moment I have set it to `g_timeout_msec` the same as for `CURLOPT_TIMEOUT_MS` which is enough to bypass my connection issue.

**Comment by fluancefg** [comment]
Ok, I've changed that line to:
`CURL_SETOPT(g_http_handle, CURLOPT_CONNECTTIMEOUT_MS, g_timeout_msec);`

It seems to be enough for the moment to bypass my connection issue.

**Comment by pramsey** [comment]
I bumped that value way down early in development of the extension because having your backend hang until the 5 minute time-out ended seemed bad (tm). I wonder if curl has an interrupt checker, that could be a good enhancement. In the meanwhile, adding this parameter to the new list of settable parameters seems wise.

**Comment by pramsey** [comment]
The timeout is user-configurable now with commits from #48

**Comment by fluancefg** [comment]
It makes sense not to keep the 300s default value. However, thanks for adding it as a user-configurable parameter.

**Comment by fluancefg** [comment]
Something weird.
In a function, I set the following options:
`SET http.timeout_msec TO 5000;`
`PERFORM http_set_curlopt('CURLOPT_CONNECTTIMEOUT', '5');`
`PERFORM http_set_curlopt('CURLOPT_TIMEOUT_MS', '5000');`
Then I run `SELECT content INTO v_content FROM http_get('someurl');`

But I still get the following error message:
`Connection timed out after 1000 milliseconds`

**Comment by fluancefg** [comment]
It seems that each time http_get_handle() function is called, it resets the `CURLOPT_CONNECTTIMEOUT` to 1.
So `curl_easy_setopt(handle, CURLOPT_CONNECTTIMEOUT, 1);` should only be called once at initialization.
