### ISSUE TITLE
Different charset

### ISSUE THREAD

**Issue by fluancefg** [pramsey/pgsql-http#49]
Hi,

I'm trying to get a page for which charset is defined to iso8859-1. But with the extension, I get this kind of characters: `Probl�me`.

Using curl on the command line, I can pipe the result to the following command `iconv -f iso8859-1 -t utf-8` which does the job perfectly.

How can I achieve that with the extension ?

**Comment by pramsey** [comment]
Any chance you have a public URL that does this? would make debug/fix faster.

**Comment by fluancefg** [comment]
Unfortunytely, I can't publish this URL on github because it's sensitive. I've sent it to to your private email.

**Comment by fluancefg** [comment]
It works very well, goob job.

Thanks
