### ISSUE TITLE
Release 1.2.1

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-http#51]
@pramsey  I'm in middle of installing all my favorite exntesions for PostgreSQL 10.  Are you planning to do another release soon like a 1.2.1, or should I just go with 1.2.0.

1.2.0 works fine I think.

**Comment by pramsey** [comment]
Ok done https://github.com/pramsey/pgsql-http/releases/tag/v1.2.1

**Comment by robe2** [comment]
Are you gonna rerelease now that you have that issue fixed?

**Comment by pramsey** [comment]
https://github.com/pramsey/pgsql-http/releases/tag/v1.2.1
