### ISSUE TITLE
Undefined reference to strcastestr

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-http#52]
@pramsey  I'm sorry I guess I didn't test master before you released and didn't think things would break.
I got below trying to compile 1.2.1 you just released.  switching back to  1.2.0 compiled fine.

This is building with curl 7.48.0, 

Might have to do with you new reliance on libcrypto.  I'm going to compile with that enabled.
Before you didn't have a direct dependence on OpenSSL, so I could swap in and out with a curl that had or didn't have SSL support.

```
> rm -rf results/ regression.diffs regression.out tmp_check/ tmp_check_iso/ log/ output_iso/
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2  -I/projects/curl/rel-curl-7.48.0w64gcc48/include -I/projects/pcre/rel-8.33w64gcc48/include -I/projects/libxml/rel-libxml2-2.7.8w64gcc48/include/libxml2 -I. -I./ -IC:/MING64~1/projects/POSTGR~1/rel/PG10W6~2/include/server -IC:/MING64~1/projects/POSTGR~1/rel/PG10W6~2/include/internal  -I.  -I/projects/curl/rel-curl-7.48.0w64gcc48/include -I/projects/libxml/rel-libxml2-2.7.8w64gcc48/include/libxml2 -I/projects/pcre/rel-8.33w64gcc48/include -IC:/MING64~1/projects/POSTGR~1/rel/PG10W6~2/include/server/port/win32  -c -o http.o http.c
http.c: In function 'http_request':
http.c:912:5: warning: implicit declaration of function 'strcasestr' [-Wimplicit-function-declaration]
     if ( strcasestr(param, paramtype) )
     ^
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2   -shared -static-libgcc -o http.dll  http.o -LC:/MING64~1/projects/POSTGR~1/rel/PG10W6~2/lib -Wl,--allow-multiple-definition -Wl,--disable-auto-import -L/projects/libxml/rel-libxml2-2.7.8w64gcc48/lib  -Wl,--as-needed   -L/projects/curl/rel-curl-7.48.0w64gcc48/lib -L/projects/libxml/rel-libxml2-2.7.8w64gcc48/lib -L/projects/pcre/rel-8.33w64gcc48/lib -lpostgres -lpgport -lcurl -lxml2 -lregex -lpgcommon -lpgport -lxml2 -lws2_32 -lm  -lws2_32 -Wl,--export-all-symbols -Wl,--out-implib=libhttp.a
http.o: In function `http_request':
C:\ming64gcc48\projects\postgresql\extensions\pgsql_http/http.c:912: undefined reference to `strcasestr'
collect2.exe: error: ld returned 1 exit status
C:/MING64~1/projects/POSTGR~1/rel/PG10W6~2/lib/pgxs/src/MAKEFI~1/../../src/Makefile.shlib:372: recipe for target 'http.dll' failed
make: *** [http.dll] Error 1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2   -shared -static-libgcc -o http.dll  http.o -LC:/MING64~1/projects/POSTGR~1/rel/PG10W6~2/lib -Wl,--allow-multiple-definition -Wl,--disable-auto-import -L/projects/libxml/rel-libxml2-2.7.8w64gcc48/lib  -Wl,--as-needed   -L/projects/curl/rel-curl-7.48.0w64gcc48/lib -lcurl -lssl -lcrypto -lssl -lcrypto -lgdi32 -lwldap32 -lws2_32 -LC:/MING64~1/projects/POSTGR~1/rel/PG10W6~2/lib -lpostgres -lpgcommon -lpgport -lxml2 -lws2_32 -lm  -lws2_32 -Wl,--export-all-symbols -Wl,--out-implib=libhttp.a
C:/ming64gcc48/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lssl
C:/ming64gcc48/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcrypto
C:/ming64gcc48/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lssl
C:/ming64gcc48/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcrypto
collect2.exe: error: ld returned 1 exit status
C:/MING64~1/projects/POSTGR~1/rel/PG10W6~2/lib/pgxs/src/MAKEFI~1/../../src/Makefile.shlib:372: recipe for target 'http.dll' failed
make: *** [http.dll] Error 1
```

**Comment by pramsey** [comment]
I don't see why this would happen... postgis uses `strcasestr` all the time and doesn't seem to have special handling of it. It's defined in `string.h` which I am including... if you `man strcasestr` in mingw64 does it tell you what header it's defined in?

**Comment by robe2** [comment]
See

https://trac.osgeo.org/postgis/changeset/12989

**Comment by pramsey** [comment]
Also, look at the code, I'm pretty sure I have no particular ssl requirements. It's possible the curl you are linking *does* have those requirements and you aren't satisfying them?

**Comment by pramsey** [comment]
Yeah, that changeset is mostly gone now. It's not in trunk, just the configure test, but no supporting code for it anymore.

**Comment by robe2** [comment]
If nothing changed with ssl requirements, how come swapping back to 1.2.0 and changing nothing else doesn't raise the issue.

**Comment by pramsey** [comment]
You tell me :) The ssl stuff doesn't show until the linking step, which is controlled by the build info coming from pg_config. If you're building against a different pgsql install you'd get different stuff coming from pg_config. The Makefile in this repo is effectively unchanged since Nov 2015, so.

**Comment by robe2** [comment]
I'm literally just replacing -b 1.2.0 with -b 1.2.1  so compiling against the same everything else including postgresql version 10.
Okay I think I fixed it.   I'm not sure why the strcasestr screws up everything, but adding this to http.c at top (copying from postgis) fixed everything

> #ifndef HAVE_STRCASESTR
	extern char *strcasestr(const char *s, const char *find);
#endif

#ifndef HAVE_STRCASESTR
char *strcasestr(const char *s, const char *find)
{
  char c, sc;
  size_t len;

  if ((c = *find++) != 0) {
    c = tolower((unsigned char)c);
    len = strlen(find);
    do {
      do {
        if ((sc = *s++) == 0)
          return (NULL);
      } while ((char)tolower((unsigned char)sc) != c);
    } while (strncasecmp(s, find, len) != 0);
    s--;
  }
  return ((char *)s);
}
#endif

So if you want you can default it to something and I'll override in my make install or you can come up with some way of checking for it's existence without resorting to a whole ./configure thing.  Not sure how many other platforms would be affected.

**Comment by pramsey** [comment]
I added a re-named version since we cannot autodetect it.

**Comment by pramsey** [comment]
Tell me when you're happy w/ master and I'll re-tag

**Comment by robe2** [comment]
Did you push.  Doesn't look like master has changed.  Still shows Sept 9th as last update and compile still fails.

**Comment by pramsey** [comment]
Sorry, it's in 1701f986a15f8032adaac4884bce68d3cc605277

**Comment by robe2** [comment]
okay it compiles now but tests are failing and the tests don't insall the extension.  They are failing when I use 1.20 too so that's not new.
I can install the extension fine though manually  and running:

`SELECT * FROM http_get('http://postgis.net');`

works fine.


Is there supposed to be an "expected" folder.  I don't have one.

`============== running regression test queries        ==============
test http                     ... The system cannot find the path specified.
diff: C:/ming64gcc48/projects/postgresql/extensions/pgsql_http/expected/http.out: No such file or directory
diff: C:/ming64gcc48/projects/postgresql/extensions/pgsql_http/results/http.out: No such file or directory
diff command failed with status 2: diff -w "C:/ming64gcc48/projects/postgresql/extensions/pgsql_http/expected/http.out" "C:/ming64gcc48/projects/postgresql/extensions/pgsql_http/results/http.out" > "C:/ming64gcc48/projects/postgresql/extensions/pgsql_http/results/http.out.diff"
`

**Comment by pramsey** [comment]
Yeah, are there actually tests? :)
