### ISSUE TITLE
Issues when using custom search_path, the type "http_response" is not prefixed

### ISSUE THREAD

**Issue by fnicollet** [pramsey/pgsql-http#59]
Hello,

Not a big issue, but we use pgsql-http in a symfony application, which seem to use a custom search_path when updating entities in the database (probably the ORM which does that). We have an UPDATE trigger on a table managed by symfony. It kind of works, but there is an error with inline the http_response type. 
After installing (on Ubuntu), if you check the SQL of the http function, you get
```sql
CREATE OR REPLACE FUNCTION public.http(request http_request)
  RETURNS http_response AS
'$libdir/http', 'http_request'
  LANGUAGE c VOLATILE
  COST 1;
ALTER FUNCTION public.http(http_request)
  OWNER TO postgres;
```
the function is prefixed, but not the return type (it should be  public.http_response I believe)
In my trigger, I had to do beforehand
```sql
SET search_path TO 'public';
```
And at the end, set it back to the symfony search path, which is not ideal (but works :) ).

Fabien

**Comment by pramsey** [comment]
You could permanently alter the search path on the function itself... 
```
ALTER FUNCTION http(http_request) SET search_path = public;
```

**Comment by pramsey** [comment]
I'm not sure I want to change to code to make the function work in odd search path cases... it'll add a certain amount of ugliness and remove some flexibility around relocateability. Will have to think on it.

**Comment by fnicollet** [comment]
Thanks!

It is a bit of an edge case really, but at least if people look for the issue on github, they can find a workaround. You can close this issue if not a priority, no problem
