### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by KazarinAY** [pramsey/pgsql-http#60]
I have PostgreSQL devel packages and CURL devel packages installed (postgresql-devel-9.2.23-3.el7_4.x86_64 and libcurl-devel-7.29.0-42.el7_4.1.x86_64).
When I run make, I get this:
`
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o http.o http.c
http.c:169:1: error: unknown type name «pqsigfunc»
 pqsigfunc pgsql_interrupt_handler = NULL;
 ^
http.c: In function «_PG_init»:
http.c:240:2: Warning: implicit declaration of function «pqsignal» [-Wimplicit-function-declaration]
  pgsql_interrupt_handler = pqsignal(SIGINT, http_interrupt_handler);
  ^
In file included from /usr/include/curl/curl.h:2227:0,
                 from http.c:69:
http.c: In function «http_request»:
http.c:854:29: error: «CURLOPT_XFERINFOFUNCTION» undeclared (first use in this function)
  CURL_SETOPT(g_http_handle, CURLOPT_XFERINFOFUNCTION, http_progress_callback);
                             ^
http.c:854:2: Warning: in expansion of macro «CURL_SETOPT»
  CURL_SETOPT(g_http_handle, CURLOPT_XFERINFOFUNCTION, http_progress_callback);
  ^
http.c:854:29: Warning: each undeclared identifier is reported only once for each function it appears in
  CURL_SETOPT(g_http_handle, CURLOPT_XFERINFOFUNCTION, http_progress_callback);
                             ^
http.c:854:2: Warning: in expansion of macro «CURL_SETOPT»
  CURL_SETOPT(g_http_handle, CURLOPT_XFERINFOFUNCTION, http_progress_callback);
  ^
http.c:982:5: error: invalid type argument of unary «*» (have «int»)
    (*pgsql_interrupt_handler)(http_interrupt_requested);
     ^
http.c: In function «typname_get_tupledesc»:
http.c:525:1: Warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [http.o] Error 1

`

**Comment by pramsey** [comment]
You have a very old version of pgsql and curl, I think your install is just way older than supported.
