### ISSUE TITLE
Release on PGXN

### ISSUE THREAD

**Issue by theory** [pramsey/pgsql-http#61]
Any chance you’d be willing to release this on PGXN, Paul? Would make it easier for our automated build stuff to grab, build, and install. Plus the docs would look cool!

**Comment by pramsey** [comment]
Every time I consider it, I bump on the idea that "upload your package to PGXN" is a step. Why isn't it just "give PGXN the URL to your META.json and have the JSON include the link to the latest source"? I'm just too lazy have have another release step. Am I missing an obvious aspect of PGXN?

**Comment by theory** [comment]
Central place to find all your stuff? Also, I myself just use the PGXN utils to do releases, so it’s just `pgxn bundle thing` and `pgxn release thing`. Also, @decibel has made various `Makefile` utilities to handle the `META.json` handling.

But honestly, I think it’s useful for folks to be able to search for and find all their Postgres extension in one place, read the docs, etc. In my mind, at least, that *is* the release, but then I would say that, it’s my baby and I’ve been doing the same thing with CPAN modules since forever.

It would be cool to write a little thing that periocially looked for updated META.json files and Github and uploaded stuff. But it would make me a little nervous, since a Meta.json change isn’t necessarily the same as a release.s

**Comment by pramsey** [comment]
A change in the release number in meta.json seems like a strong signal to "download", no?

**Comment by pramsey** [comment]
Or, if the META.json is registered for the project, a simple button on the PGXN page for the administrator "release", so that there's no "upload" step, just a one-click-update.

**Comment by W1M0R** [comment]
I see that version 1.3.0 is uploaded to PGXN: https://pgxn.org/dist/http/

Would you mind updating it to version 1.3.1?

**Comment by pramsey** [comment]
Yeah, it won't accept my META.json even though it links fine. I really hate that pgxn requires me to constantly manually update it, I should be able to give it a github URL and it should check for new releases automatically.
```
Cannot parse JSON from “pgsql-http-1.3.1/META.json”: '"' expected, at character offset 699 (before "},\n "resources": ...")
```

**Comment by theory** [comment]
I would like that feature too, @pramsey, but my tuits are in quite short supply to make it happen. Do you know anyone with the time and wherewithal to add such a feature?

**Comment by theory** [comment]
The JSON file in the repo is fine, but the one in the 1.3.1 zip file has a wayward comma:

``` json
   "provides": {
     "http": {
       "file": "http--1.3.sql",
       "docfile": "README.md",
       "version": "1.3",
       "abstract": "HTTP client for PostgreSQL"
     }, <---- remove me
   },
```

**Comment by theory** [comment]
FYI, I wrote about using GitHub actions to automate releasing an extension on both GitHub and PGXN in [a post](https://justatheory.com/2020/10/release-postgres-extensions-with-github-actions/) a few days ago.
