### ISSUE TITLE
[Err] server closed the connection unexpectedly

### ISSUE THREAD

**Issue by sbvalijon** [pramsey/pgsql-http#70]
I am sending put request to elasticsearch service from postgresql.
```
SELECT status, content_type
  FROM http_put('http://localhost:9200/merchant_index_dev/merchant/45cb81fe-647e-4a8d-934a-8f4cccf881bf', '{
    "id" : "45cb81fe-647e-4a8d-934a-8f4cccf881bf",
    "name" : "Test merchant indexed from postgres"
}', 'application/json');
```
It is working fine(indexes a new doc with given id). However I am getting the following error at pg side:
```
[SQL]
SELECT status, content_type
  FROM http_put('http://localhost:9200/merchant_index_dev/merchant/45cb81fe-647e-4a8d-934a-8f4cccf881bf', '{
    "id" : "45cb81fe-647e-4a8d-934a-8f4cccf881bf",
    "name" : "Test merchant indexed from postgres"
}', 'application/json');

[Err] server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

**Comment by sbvalijon** [comment]
Same request with post worked fine:
```
SELECT status, content_type
  FROM http_post('http://localhost:9200/merchant_index_dev/merchant/45cb81fe-647e-4a8d-934a-8f4cccf881bf', '{
    "id" : "45cb81fe-647e-4a8d-934a-8f4cccf881bf",
    "name" : "Test merchant indexed from postgres"
}', 'application/json');
```
Elasticsearch service is ok, because if I send the same PUT request from curl it gives success message..
P.S. both pg and elasticsearch are in the same machine

**Comment by pramsey** [comment]
Looks like a crash. Are you working off the master?

**Comment by pramsey** [comment]
Does the same thing happen on a non-Elasticsearch endpoint? I cannot get a crash testing httpbin
```
SELECT status, content_type
  FROM http_put('http://httpbin.org/anything', '{
    "id" : "45cb81fe-647e-4a8d-934a-8f4cccf881bf",
    "name" : "Test merchant indexed from postgres"
}', 'application/json');
```

**Comment by sbvalijon** [comment]
With my Spring boot project that worked fine.  However, http_put is throwing error with elasticsearch REST API.

**Comment by pramsey** [comment]
Is there any public elastic search instance you can use to demonstrate this? I'm not exciting about setting my own ES instance up just to verify that I can duplicate the issue. The easier you make this for me, the more likely it is I will fix it for you. Or, do a PR yourself :)

**Comment by pramsey** [comment]
This may be the same as #75 and hopefully gone now.
