### ISSUE TITLE
How to upgrade to 1.2.4 release on Windows

### ISSUE THREAD

**Issue by extraplas** [pramsey/pgsql-http#77]
Hi, and thanks for your very useful  extension. I'm using pgsql-http to invoke soap requests.
I have installed the 1.2.2 release by the latest Windows installation package available on the "unofficial" source. I would like to upgrade to the newest 1.2.4 because I need to hold curlopt_cainfo option through the whole database connection session in order to call multiple soap requests at a time. 
How can I easily do that (I'm not a hacker!)?
Thanks

**Comment by pramsey** [comment]
Perhaps @robe2 will build new ones when PgSQL 11 comes out.
