### ISSUE TITLE
Got SSL certificate problem for HTTPS calls

### ISSUE THREAD

**Issue by ih-gopinathk** [pramsey/pgsql-http#78]
Hi, 

Thanks for your great & useful extension. I am a data analyst, using your extension to pull the data from Web Services. 
I am using pg10 version of EDB and installed pgsql-http v1.2.2 in windows 64-bit. This extension very helpful for me to pull the data from http Site. 
Whenever I execute an API URL with secure connection like "select * from http_get('https://url......')", getting an error saying that "SSL certificate problem: unable to get local issuer certificate". 
Please let me know the possible solutions for it.

**Comment by extraplas** [comment]
I use pgsql-http for the same job.
For secure connections (https://) you have to:
1) put the provided file "ca-bundle.crt" in the (new) folder "C:/ssl/certs"
2) before your script, you have to set this curl option: "SELECT http_set_curlopt('CURLOPT_CAINFO', 'C:/ssl/certs/ca-bundle.crt');"
It works for me. The only problem, as said in issue #77, is that you can do just one call with a single script. For unsecure connections (http://) I can do many calls with a single script.
For responses with a big amount of data  i also suggest you to set the "http.timeout_msec" GUC variable. Finally my code is:
SET http.timeout_msec = 59000; -- set the timeout at 59 seconds (or less; or more)
SELECT http_set_curlopt('CURLOPT_CAINFO', 'C:/ssl/certs/ca-bundle.crt'); -- provide CA certificate for secure connection
SELECT .... -- my http request

**Comment by ih-gopinathk** [comment]
Great. Working... 
Many thanks.
