### ISSUE TITLE
Compile on Centos 

### ISSUE THREAD

**Issue by AmrSaid** [pramsey/pgsql-http#79]
we have a problem in compiling for Centos 6.9 and postgreSQL version 10.4
after make we have the below output 

make
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -DLINUX_OOM_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -fno-strict-aliasing -fwrapv -fpic -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o http.o http.c
http.c:50:32: error: commands/extension.h: No such file or directory
http.c: In function ‘_PG_init’:
http.c:270: error: too many arguments to function ‘DefineCustomBoolVariable’
http.c:283: error: too many arguments to function ‘DefineCustomIntVariable’
http.c: In function ‘header_array_to_slist’:
http.c:465: error: ‘ArrayIterator’ undeclared (first use in this function)
http.c:465: error: (Each undeclared identifier is reported only once
http.c:465: error: for each function it appears in.)
http.c:465: error: expected ‘;’ before ‘iterator’
http.c:466: warning: ISO C90 forbids mixed declarations and code
http.c:472: error: ‘iterator’ undeclared (first use in this function)
http.c:472: warning: implicit declaration of function ‘array_create_iterator’
http.c:475: warning: implicit declaration of function ‘array_iterate’
http.c:543: warning: implicit declaration of function ‘array_free_iterator’
http.c: In function ‘typname_get_tupledesc’:
http.c:556: warning: implicit declaration of function ‘get_extension_oid’
http.c:565: warning: implicit declaration of function ‘GetSysCacheOid2’
http.c:572: warning: implicit declaration of function ‘getExtensionOfObject’
http.c: In function ‘http_request’:
http.c:959: error: ‘CURLOPT_ACCEPT_ENCODING’ undeclared (first use in this function)
http.c:959: warning: type defaults to ‘int’ in declaration of ‘_curl_opt’
http.c:1183: warning: implicit declaration of function ‘pg_any_to_server’
http.c:1183: warning: assignment makes pointer from integer without a cast
make: *** [http.o] Error 1

**Comment by pramsey** [comment]
Since `extension.h` seems to exist in the same place in all versions of PgSQL, my diagnosis is that you haven't installed the development headers on your system.
```
postgresql-9.2.10/src/include/commands/extension.h
postgresql-9.3.9/src/include/commands/extension.h
postgresql-9.4.5/src/include/commands/extension.h
postgresql-9.5.4/src/include/commands/extension.h
postgresql-9.6.2/src/include/commands/extension.h
postgresql-git/src/include/commands/extension.h
```
The package name will be something like "postgresql-devel" or "postgresql-server-devel".

**Comment by pramsey** [comment]
(Or alternately, whoever packaged your RPM failed to include that header? Seems unlikely, but do confirm the existence of `commands/extension.h`)

**Comment by AmrSaid** [comment]
Hello Pramsey,
Thank you so much for your reply. actually only the extension.h is missing all headers exist in this path at my server /usr/include/pgsql/server/ 
and the commands folder holds different header file but extension.h is not there.
I already installed the development package and installed it. 
if I do ls -l on the commands folder you can find the below header files
ls -l
-rw-r--r--. 1 root root  712 Oct  5  2017 alter.h
-rw-r--r--. 1 root root 1565 Oct  5  2017 async.h
-rw-r--r--. 1 root root  973 Oct  5  2017 cluster.h
-rw-r--r--. 1 root root 1362 Oct  5  2017 comment.h
-rw-r--r--. 1 root root  911 Oct  5  2017 conversioncmds.h
-rw-r--r--. 1 root root  701 Oct  5  2017 copy.h
-rw-r--r--. 1 root root 2063 Oct  5  2017 dbcommands.h
-rw-r--r--. 1 root root 6494 Oct  5  2017 defrem.h
-rw-r--r--. 1 root root  530 Oct  5  2017 discard.h
-rw-r--r--. 1 root root 1698 Oct  5  2017 explain.h
-rw-r--r--. 1 root root  619 Oct  5  2017 lockcmds.h
-rw-r--r--. 1 root root  985 Oct  5  2017 portalcmds.h
-rw-r--r--. 1 root root 2306 Oct  5  2017 prepare.h
-rw-r--r--. 1 root root  833 Oct  5  2017 proclang.h
-rw-r--r--. 1 root root  946 Oct  5  2017 schemacmds.h
-rw-r--r--. 1 root root 2568 Oct  5  2017 sequence.h
-rw-r--r--. 1 root root 2090 Oct  5  2017 tablecmds.h
-rw-r--r--. 1 root root 1604 Oct  5  2017 tablespace.h
-rw-r--r--. 1 root root 6225 Oct  5  2017 trigger.h
-rw-r--r--. 1 root root 1648 Oct  5  2017 typecmds.h
-rw-r--r--. 1 root root  819 Oct  5  2017 user.h
-rw-r--r--. 1 root root 6025 Oct  5  2017 vacuum.h
-rw-r--r--. 1 root root 1404 Oct  5  2017 variable.h
-rw-r--r--. 1 root root  516 Oct  5  2017 version.h
-rw-r--r--. 1 root root  570 Oct  5  2017 view.h

should I only get this header and add it manually, I am not sure if there is a change for that but I will give it a try.

**Comment by AmrSaid** [comment]
Hello,

I added now the extension.h from the source but obviously there different versions not compatible with each other.
make
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -DLINUX_OOM_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -fno-strict-aliasing -fwrapv -fpic -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o http.o http.c
In file included from http.c:50:
/usr/include/pgsql/server/commands/extension.h:17:35: error: catalog/objectaddress.h: No such file or directory
In file included from http.c:50:
/usr/include/pgsql/server/commands/extension.h:34: error: expected ‘)’ before ‘*’ token
/usr/include/pgsql/server/commands/extension.h:43: error: expected ‘)’ before ‘*’ token
/usr/include/pgsql/server/commands/extension.h:45: error: expected ‘)’ before ‘*’ token
http.c: In function ‘_PG_init’:
http.c:270: error: too many arguments to function ‘DefineCustomBoolVariable’
http.c:283: error: too many arguments to function ‘DefineCustomIntVariable’
http.c: In function ‘header_array_to_slist’:
http.c:465: error: ‘ArrayIterator’ undeclared (first use in this function)
http.c:465: error: (Each undeclared identifier is reported only once
http.c:465: error: for each function it appears in.)
http.c:465: error: expected ‘;’ before ‘iterator’
http.c:466: warning: ISO C90 forbids mixed declarations and code
http.c:472: error: ‘iterator’ undeclared (first use in this function)
http.c:472: warning: implicit declaration of function ‘array_create_iterator’
http.c:475: warning: implicit declaration of function ‘array_iterate’
http.c:543: warning: implicit declaration of function ‘array_free_iterator’
http.c: In function ‘typname_get_tupledesc’:
http.c:565: warning: implicit declaration of function ‘GetSysCacheOid2’
http.c:572: warning: implicit declaration of function ‘getExtensionOfObject’
http.c: In function ‘http_request’:
http.c:959: error: ‘CURLOPT_ACCEPT_ENCODING’ undeclared (first use in this function)
http.c:959: warning: type defaults to ‘int’ in declaration of ‘_curl_opt’
http.c:1183: warning: implicit declaration of function ‘pg_any_to_server’
http.c:1183: warning: assignment makes pointer from integer without a cast
make: *** [http.o] Error 1

what do you suggest? Have this code tested before on version PostgreSQL 10.4 or it is first time?

Thank you so much in advance for your cooperation.

BR,
Amr

**Comment by pramsey** [comment]
This code works fine against 10 and 11. There's something different with your environment. The list of headers in `commands` for my install of 10 has quite a few more files.
```
-rw-r--r--  1 pramsey  staff  1137 23 Jul 06:08 alter.h
-rw-r--r--  1 pramsey  staff  1655 23 Jul 06:08 async.h
-rw-r--r--  1 pramsey  staff  1271 23 Jul 06:08 cluster.h
-rw-r--r--  1 pramsey  staff   811 23 Jul 06:08 collationcmds.h
-rw-r--r--  1 pramsey  staff  1413 23 Jul 06:08 comment.h
-rw-r--r--  1 pramsey  staff   649 23 Jul 06:08 conversioncmds.h
-rw-r--r--  1 pramsey  staff  1541 23 Jul 06:08 copy.h
-rw-r--r--  1 pramsey  staff   913 23 Jul 06:08 createas.h
-rw-r--r--  1 pramsey  staff  1258 23 Jul 06:08 dbcommands.h
-rw-r--r--  1 pramsey  staff  1202 23 Jul 06:08 dbcommands_xlog.h
-rw-r--r--  1 pramsey  staff  6998 23 Jul 06:08 defrem.h
-rw-r--r--  1 pramsey  staff   475 23 Jul 06:08 discard.h
-rw-r--r--  1 pramsey  staff  3433 23 Jul 06:08 event_trigger.h
-rw-r--r--  1 pramsey  staff  3878 23 Jul 06:08 explain.h
-rw-r--r--  1 pramsey  staff  2030 23 Jul 06:08 extension.h
-rw-r--r--  1 pramsey  staff   563 23 Jul 06:08 lockcmds.h
-rw-r--r--  1 pramsey  staff   942 23 Jul 06:08 matview.h
-rw-r--r--  1 pramsey  staff  1048 23 Jul 06:08 policy.h
-rw-r--r--  1 pramsey  staff   907 23 Jul 06:08 portalcmds.h
-rw-r--r--  1 pramsey  staff  2178 23 Jul 06:08 prepare.h
-rw-r--r--  1 pramsey  staff   635 23 Jul 06:08 proclang.h
-rw-r--r--  1 pramsey  staff  1402 23 Jul 06:08 progress.h
-rw-r--r--  1 pramsey  staff   943 23 Jul 06:08 publicationcmds.h
-rw-r--r--  1 pramsey  staff   937 23 Jul 06:08 schemacmds.h
-rw-r--r--  1 pramsey  staff   980 23 Jul 06:08 seclabel.h
-rw-r--r--  1 pramsey  staff  1857 23 Jul 06:08 sequence.h
-rw-r--r--  1 pramsey  staff   968 23 Jul 06:08 subscriptioncmds.h
-rw-r--r--  1 pramsey  staff  2944 23 Jul 06:08 tablecmds.h
-rw-r--r--  1 pramsey  staff  1961 23 Jul 06:08 tablespace.h
-rw-r--r--  1 pramsey  staff  9229 23 Jul 06:08 trigger.h
-rw-r--r--  1 pramsey  staff  2245 23 Jul 06:08 typecmds.h
-rw-r--r--  1 pramsey  staff  1297 23 Jul 06:08 user.h
-rw-r--r--  1 pramsey  staff  8035 23 Jul 06:08 vacuum.h
-rw-r--r--  1 pramsey  staff  1885 23 Jul 06:08 variable.h
-rw-r--r--  1 pramsey  staff   721 23 Jul 06:08 view.h
```

**Comment by AmrSaid** [comment]
Hello Pramsey,
 I have installed a fresh server with PostgreSQL 9.6 on Centos 7 and was able to compile it successfully. Thanks for your support. very much appreciated.
BR,
Amr

**Comment by pramsey** [comment]
Glad to know it worked out.
