### ISSUE TITLE
POST doesn't seem to work as expected

### ISSUE THREAD

**Issue by ksrinivs64** [pramsey/pgsql-http#8]
Hi I was trying a simple test with a simple web server using the http_post('http://localhost:8080/test', 'name=foo', '/text/plain') and it does seem to call post on the web server side, but I don't seem to be able to get the value of the parameter passed in correctly.  I verified that curl --data "name=foo" http:localhost:8080/test does hit the web server and the values are passed correctly.  Is there anything obviously wrong in how I am invoking http_post?

**Comment by pramsey** [comment]
Try setting your content type to application/x-www-form-urlencoded instead? 

P

**Comment by ksrinivs64** [comment]
That worked like a charm!  Thanks very much for your quick response.  I really like your package!
