### ISSUE TITLE
CURLOPT_SSLCERT not available for run-time configuration

### ISSUE THREAD

**Issue by Fransie** [pramsey/pgsql-http#81]
When executing http_get(), in one case I get the error "ERROR:  SSL certificate problem: self signed certificate in certificate chain". I am trying to fix that by setting CURL option CURLOPT_SSLCERT, like this:
`SELECT http_set_curlopt('CURLOPT_SSLCERT', 'c:\Windows\cacert.pem')`
This results in an error:
`ERROR:  curl option 'CURLOPT_SSLCERT' is not available for run-time configuration`

Is it always impossible to set CURLOPT_SSLCERT like this? Or could it be my particular configuration?

**Comment by pramsey** [comment]
The ability to set those options was only added 3 months ago, so it's possible your build doesn't have them yet. Try a more recent build?
