### ISSUE TITLE
PATCH method dont exist

### ISSUE THREAD

**Issue by dmpvost** [pramsey/pgsql-http#83]
Hi ;)

Is it possible to add PATCH method ? I had to make a PATCH, but the lib didn't include this possibility

thank

**Comment by myddrin** [comment]
I am not very familiar with the use PATCH, but you should be able to use `http(request http_request) ` and create your own http_patch.

From what I remember PATCH is similar to POST so, if you look at the code you can see:
`CREATE OR REPLACE FUNCTION http_post(uri VARCHAR, content VARCHAR, content_type VARCHAR)
  	RETURNS http_response
  	AS $$ SELECT http(('POST', $1, NULL, $3, $2)::http_request) $$
LANGUAGE 'sql';`

**Comment by dmpvost** [comment]
you are right, it's not the same that post, but there is not a big different. Depending how the owner build API.

I have already try to use http with PATCH but,
First I had an error, error from http_method_check.

so I have update the constraint : 

ALTER DOMAIN http_method DROP CONSTRAINT http_method_check;
ALTER DOMAIN http_method ADD CHECK (
    VALUE ILIKE 'get' OR
    VALUE ILIKE 'post' OR
    VALUE ILIKE 'patch' OR
    VALUE ILIKE 'put' OR
    VALUE ILIKE 'delete' OR
    VALUE ILIKE 'head'
);


Now It look like it work, but I saw that http use GET as default behavior, because the API send me the result from GET method and not the PATCH method.

Maybe I forgot something? Or there is a "else" default case in your code which use "GET"?

**Comment by myddrin** [comment]
I didn't realise the C part didn't support Patch as well...

Then I don't have an easy solution. You would need to also extend the http_method enum and how it's used in`http_request()` (around line 1040) . The `request_type()` function is the one defaulting to GET when the method is not known.

But you may have to use a custom request in curl to handle the PATCH verb (https://curl.haxx.se/mail/lib-2016-08/0111.html)

**Comment by dmpvost** [comment]
Okay, I have an other solution for now, to use curl with bash or python.

But it is possible to think about add PATCH on this library once?  ;) I'm not very familiar with C
If it's possible thank, otherwise I will manage without ^^ ;)

**Comment by pramsey** [comment]
Done at 60104554f40931299c58208fb3eedd71fd7dae5c

**Comment by dmpvost** [comment]
thank! I will try it soon ;)

**Comment by dmpvost** [comment]
Work perfectly! Big thank!
