### ISSUE TITLE
/tmp/plgo719346663/pl.go:13:33: fatal error: access/htup_details.h: No such file or directory  #include "access/htup_details.h"

### ISSUE THREAD

**Issue by mctenreiro** [pramsey/pgsql-http#86]
Hi my friend,
I got the error to compile:

/tmp/plgo719346663/pl.go:13:33: fatal error: access/htup_details.h: No such file or directory
 #include "access/htup_details.h"

What's happend???

**Comment by pramsey** [comment]
No idea, you haven't told me your OS, your pgsql version, whether you installed the postgresql-devel packages (that include that header)...
