### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by brandonros** [pramsey/pgsql-http#88]
I wonder how many requests per second https://github.com/PostgREST/postgrest serving a stored procedure that uses https://github.com/plv8/plv8 in conjunction with https://github.com/pramsey/pgsql-http would compare to a node.js server using https://github.com/brianc/node-postgres and https://github.com/request/request-promise-native would compare.

Any thoughts? I'll do the research, but I wanted to hear opinions from somebody who has deeper knowledge in the topic up front.

**Comment by pramsey** [comment]
I find it hard to imagine the rate limiting step will ever be other than just the overhead in doing HTTP handshakes, etc, that all the solutions would have.

**Comment by brandonros** [comment]
https://github.com/plv8/plv8/issues/301#issuecomment-430472077

**Comment by JerrySievert** [comment]
I'm really having a hard time figuring out what you're trying to measure here.
