### ISSUE TITLE
Missing regex dependency mention in instructions

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-http#9]
regex.h at least for mingw doesn't exist and I presume won't exist by default for VC++ builds either, so  should be mentioned as a requirement.

  So gives a 

can't find regex.h file when trying to compile under mingw64.

I was able to get it to compile by swapping out regex dependency with pcre and get it to compile with this hack

http://go.kblog.us/2013/02/compiling-pcre-library.html

Though I'm running into issues now trying to get it to run under PostgreSQL 9.4.  That might be separate or related.

**Comment by pramsey** [comment]
Maybe I should replace with https://github.com/cesanta/slre or you could build with http://gnuwin32.sourceforge.net/packages/regex.htm?

**Comment by robe2** [comment]
I tried building regex package and got all sorts of errors so I gave up on regex (gnuwin32) and the other source was the whole glibc which is huge.  Anyway the pcre hack works fine -- see my other bug ticket.

**Comment by pramsey** [comment]
Aha, I see the answer, as usual, there's support built right into PostgreSQL, `include/regex/regex.h`

**Comment by pramsey** [comment]
And it turns out it's quite a PITA to use that internal regex code. This still a problem on your end?

**Comment by robe2** [comment]
nah like I said it was just instructions, but I can cleanup my instructions, if per chance any mingw people want to compile this.  I suspect itwould only affect windows people anyway.

My regex hack work's great.  All I had to do was copy a dll and a .h file and name it something else to use the pcre that I need anyway for address_standardardizer.
