### ISSUE TITLE
Resolving timed out after 1523 milliseconds

### ISSUE THREAD

**Issue by dmpvost** [pramsey/pgsql-http#90]
Hi,

I have often too much problem with resolving time out, 
Do you have any advice to avoid it, or how configure it ?

I have program a while 5 retry in case of : 
- Connection timed out
- Resolving timed out
- Operation timed out

So it work, but generally the total need is about 2500ms finally

I put this on my config

SELECT http_reset_curlopt();
SET http.timeout_msec = 20000;
SET http.dns_server = '1.1.1.1';
SET http.keepalive = 'on';

SELECT http_set_curlopt('CURLOPT_TIMEOUT', '20000');

VERSION 1.3.0

thank

**Comment by pramsey** [comment]
Don't bother with the GUC values, just use http_set_curlopt().
```
http_set_curlopt('CURLOPT_TIMEOUT', '20');
http_set_curlopt('CURLOPT_TCP_KEEPALIVE', '20');
```
The [CURLOPT_DNS_SERVERS](https://curl.haxx.se/libcurl/c/CURLOPT_DNS_SERVERS.html) option is not currently supported.

**Comment by pramsey** [comment]
Added it as an option at 15a44d299979df50e9ea1478ab3c0f0a5059dba6

**Comment by dmpvost** [comment]
Where do you put this configuration? I use it directly from SQL, that why I use SELECT....

What it is GUC?

**Comment by pramsey** [comment]
Put it at the start of your session, just run it in SQL, I've edited for clarity, sorry.

**Comment by dmpvost** [comment]
Ok thank! 

On each session? it's not saved?

I have thinking that it's save forever for all the database.

If it's not save.. I will make a function that call my configuration

**Comment by pramsey** [comment]
It will not save, make that function :)

**Comment by dmpvost** [comment]
Oh okay!  I understand my problem now! thank!

**Comment by dmpvost** [comment]
> Don't bother with the GUC values, just use http_set_curlopt().
> 
> ```
> SELECT http_set_curlopt('CURLOPT_TIMEOUT', '20');
> SELECT http_set_curlopt('CURLOPT_TCP_KEEPALIVE', '20');
> ```
> The [CURLOPT_DNS_SERVERS](https://curl.haxx.se/libcurl/c/CURLOPT_DNS_SERVERS.html) option is not currently supported.

Last question! 

Value parameters are in milli-seconds or seconds?

**Comment by pramsey** [comment]
Those ones are whole seconds. The `CURLOPT_TIMEOUT_MS` is in ms.
