### ISSUE TITLE
how could I join the result if the returned set does not contain the url?

### ISSUE THREAD

**Issue by docteurklein** [pramsey/pgsql-http#91]
Maybe I'm completely wrong (and tired), but I don't see how I could join the set returned by `http_get` if it doesn't return the url in the set.

Shouldn't a set always contain its primary key or something? I'd love to hear a set theorist explain me how wrong I am :)

I have a weird use case where I would want that.
It uses pipelinedb's continuous transforms that don't allow subselects in a query, but joins are permitted):

I found a solution for now, which is to return the whole row as a column, but would prefer to join.
```
create view content_stream with (action=transform) as
    select url, language, http_get(url) as response
    from url_stream
;

create view resources with (action=materialize) as
    select url,
    to_tsvector(coalesce(language, 'en')::regconfig, (response).content) as indexed
    from output_of('content_stream')
;
```

**Comment by docteurklein** [comment]
Another problem I get with pipelinedb is that as soon as curl logs an error (`ERROR:  SSL certificate problem: unable to get local issuer certificate` f.e), the continuous transforms siply stops. But I get that's a problem with pipelinedb?

**Comment by docteurklein** [comment]
something like this https://github.com/pramsey/pgsql-http/pull/92

**Comment by docteurklein** [comment]
now i'm able to do something like: 

```
select content from resources join http_get(uri) using (uri);
```

**Comment by pramsey** [comment]
Really don't know, sorry.
