### ISSUE TITLE
Searching for a CRITICAL Bug

### ISSUE THREAD

**Issue by dmpvost** [pramsey/pgsql-http#93]
hi!

I have a big problem somewhere, I'm still investigating for it, since 2/3 days.
I'm working with the API of STRIPE, a banking API.

When I make some call like a POST, or a GET, simply in my SQL console, no problem, everything work.

But when I have some sequential call in a function, crazy things happened.

Exemple:

I charge a customer with a POST query (with body)
After, I try to make a GET to retrieve some data to verify, The API send me an error report with, 
` Unrecognized request URL (POST: /v1/balance)`

I commented out this function, to dig, and see how it work after for my next verification, and I get the same error, just a call after in the same sequence.

So generally I'm trying to do
-> POST
-> GET (Stripe get a POST)
-> GET (Stripe get a POST)

I have check everywhere in my code, and I'm 100% sure that I'm not sending a POST.

(All my code was working before with a CURL in plpython3u)

An other bug happened time to time, same situation, I make a GET, but STRIPE said me that it's A POST, and that DATA in body are not clear. In error report I see it's a kind of binary which is send, unclear data, or a kind of bad C++ pointer?

I only use the function "http" for put all parameters myself

thank for help

**Comment by pramsey** [comment]
Can you construct an example using the http://httpbin.org/ service, so that I can see your issue in action? Do a post then a get, to the appropriate end points, see what happens.

**Comment by pramsey** [comment]
How does what work? the instructions for httpbin are on the web site, and you can see some SQL examples of call in the test directory of this extension.

**Comment by dmpvost** [comment]
I've tried, but not able to reproduce it, going back to my solution, 

I get  : `"Invalid UTF-8 characters found in POST body: \"\\xC4\"`

**Comment by pramsey** [comment]
I'm sure you have a problem, but without direct access to your computer to debug it, and without access to an example that exercises it, there's nothing I can do, I certainly do not have the time to try and recreate the condition based on the clues you've been able to provide so far.

**Comment by dmpvost** [comment]
Thank for helping, I will try more tomorrow, or during the next days! I will try to come back with more informations

**Comment by pramsey** [comment]
NP, I hope we can run this down.

**Comment by dmpvost** [comment]
Ok, I have make some others test, 
I have contact the stripe support by the way, and now, I'm pretty sure it come from the library.

`
SELECT http_reset_curlopt();
SET http.timeout_msec = 20000;
SET http.dns_server = '208.67.222.222';
SET http.keepalive = 'on';

SELECT http_set_curlopt('CURLOPT_TIMEOUT', '20');
SELECT http_set_curlopt('CURLOPT_TCP_KEEPALIVE', '20');
SELECT http_set_curlopt('CURLOPT_TIMEOUT_MS', '20000');
`


I was thinking about some remanent data from "http.keepalive = on " ? 

I get this bug of transformation GET->POST in 2/3 different call of STRIPE.

When I isolate the query alone on my console, there is no problem.
Only when I'm running it in sequence.
