### ISSUE TITLE
how to get status for http_head & http_get status from link with 1 contact?

### ISSUE THREAD

**Issue by majestique** [pramsey/pgsql-http#97]
As I understand, the `status` for `http_head` & `http_get` are different. The `status` for `http_head` follows `header` redirects and could indicate `302` while `http_get` can indicate `200` on the same url.

How can I get the `status` for both `http_head` & `http_get` on one contact to a url? I'd rather not contact it twice.

Thanks!

**Comment by pramsey** [comment]
Seems pretty impossible to me, they are distinct HTTP verbs, any given request has to be one or the other.
