### ISSUE TITLE
Doesn't compile against 12 Head

### ISSUE THREAD

**Issue by robe2** [pramsey/pgsql-http#98]
> http.c: In function 'typname_get_tupledesc':
http.c:594:49: error: macro "GetSysCacheOid2" requires 4 arguments, but only 3 given
                   ObjectIdGetDatum(typnamespace));
                                                 ^
http.c:592:16: error: 'GetSysCacheOid2' undeclared (first use in this function); did you mean 'GetSysCacheOid'?
   Oid typoid = GetSysCacheOid2(TYPENAMENSP,
                ^~~~~~~~~~~~~~~
                GetSysCacheOid
http.c:592:16: note: each undeclared identifier is reported only once for each function it appears in
http.c:591:7: warning: unused variable 'typnamespace' [-Wunused-variable]
   Oid typnamespace = lfirst_oid(l);
       ^~~~~~~~~~~~
make: *** [<builtin>: http.o] Error 1

**Comment by pramsey** [comment]
Fixed with 9fd8e9cd7e7db556c589d726ab63de1e6c4871db
